### ISSUE TITLE
Get Country / Get Bots

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#10]
Hey,

perhaps it is possible to add some functionality to show the country the server is located, and to get the Bots playing on the server :)

greetings

**Comment by koraktor** [comment]
This is possible, but right now the library should only _pipeline_ the data from the servers to the user in a comfortable way. Other high-level features (like those mentioned) will most likely be added in the future - but not in the near future.

**Comment by jouva** [comment]
You might want to look into GeoIP services for the country resolution. I feel this is out of the scope of this library and would just be feature creep, as its intent is to provide data from the server and let the user figure out what wants to be done with it.

**Comment by koraktor** [comment]
@idev: As far as I know you're using Ruby. So you might have a look at [ry/geoip-city](http://github.com/ry/geoip-city) for getting geo information. Just like jouva said, I'm most probably not going to add support for this to Steam Condenser - especially not through self-implemented code.

Concerning bots I will try to find a good way to implement this. But this is rather low priority.

**Comment by idev** [comment]
Thanks for your help guys! I will have a look into it.

**Comment by txdv** [comment]
I think geoip shouldn't be part of this library since there are already enough stand alone geoip libraries.

**Comment by koraktor** [comment]
Using the RCON powered `getPlayers()` you're now able to see if a player is a bot using its `isBot()` method. This should be sufficient.

Like said before, there are other libraries for geolocation support.
