### ISSUE TITLE
Player information - Team that the player is on ?

### ISSUE THREAD

**Issue by Mutix** [koraktor/steam-condenser#101]
Enhancement?

Would it be possible to add a "team" property to the SteamPlayer object?

Is it possible to find what team a player is on when calling the getPlayers() method on a server?

Thank you very much for this program :)

**Comment by koraktor** [comment]
I don't know of any general feature that would allow something like this, but maybe there are specific features of e.g. TF2 or CS:S that would make this possible. I'll have a look.

Thanks for the idea, and thanks for using Steam Condenser.

**Comment by koraktor** [comment]
Thanks to a hint from @BINARYADDlCT I do know (or at least I think) how HLSW achieves this. Using the remote logging features of a server your able to get more detailed information on the current game in real-time.
This will also enable us to know which team a player is on.

On the downside this will require the implementation of the remote logging (something I really want to do) but additionally limits this to servers where you have RCON access.

**Comment by abhishiv** [comment]
@koraktor tor  you mean remote logging via RCON? I though game logs were only accessible over the network via udp.

**Comment by koraktor** [comment]
@abhishiv No, not remote logging _via_ RCON, but you require at least access via RCON to enable (temporary) logging to your machine.

**Comment by nisseblink** [comment]
So have you made any progress?

**Comment by koraktor** [comment]
@nisseblink No. Right now, this seems to be a lot of work to get a small feature like this. But it will stay on the list.

**Comment by abhishiv** [comment]
For cs:go and maybe some other games you have access to backup files for
each round. So you can use them, the backup file name can also be
controlled via rcon.

On Saturday, June 1, 2013, Sebastian Staudt notifications@github.com
wrote:

> @nisseblink No. Right now, this seems to be a lot of work to get a small
> feature like this. But it will stay on the list.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Sent from Gmail Mobile

**Comment by koraktor** [comment]
So this requires file system access, right? That won't happen via Steam Condenser.

**Comment by abhishiv** [comment]
Yes, I am using ftp for that. But yeah Imo doesn't fit in steam condenser.

On Saturday, June 1, 2013, Sebastian Staudt notifications@github.com
wrote:

> So this requires file system access, right? That won't happen via Steam
> Condenser.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Sent from Gmail Mobile

**Comment by koraktor** [comment]
Finally closing this one. Sorry, but this won’t be added.
