### ISSUE TITLE
can't find any documentations?

### ISSUE THREAD

**Issue by conghd** [koraktor/steam-condenser#102]
I can't find any documentations for steam-condenser for ruby. The link http://www.rdoc.info/github/koraktor/steam-condenser seems does not work. can you help?
Thanks

**Comment by koraktor** [comment]
Seems to be a problem with rubydoc.info.
I opened up an issue for their project: lsegal/rubydoc.info#28

Thanks for reporting.

**Comment by koraktor** [comment]
@lsegal fixed this instantly. It's working again.

In case this should ever happen again there is a version of the docs for the current gem in http://www.rdoc.info/gems/steam-condenser
