### ISSUE TITLE
RCON-powered players not working for CS:S

### ISSUE THREAD

**Issue by koraktor** [koraktor/steam-condenser#103]
A user reports the following:

Parsing the status output of a CS:S server fails.

```
# userid name uniqueid connected ping loss state adr
#2 "HighMinus Gaming TV| 27045" BOT active
#62 "Mutix" STEAM_0:0:7390944 29:08 85 0 active 90.30.84.213:27005
```

And here is the (problematic) result:

```
Array ( [id] => 2 [userid] => [name] => HighMinus Gaming TV| 27045 [uniqueid] => BOT [time] => [ping] => [loss] => [state] => [adr] => active ) 
Array ( [id] => 62 [userid] => Mutix [name] => STEAM_0:0:7390944 [uniqueid] => 29:08 [time] => 85 [ping] => 0 [loss] => active [state] => 90.30.84.213:27005 ) 
```

Long story short, `GameServer.splitPlayerStatus()` isn't working as expected.

**Comment by koraktor** [comment]
This should be fixed with 79e018a8a12aca81f171a4cc25e041fc398377e7.
Waiting for feedback from the original reporter.

**Comment by koraktor** [comment]
There were some [other fixes](https://github.com/koraktor/steam-condenser/compare/79e018a8a1...1e632cd5a7) further improving the status parsing.

**Comment by Mutix** [comment]
Latest commits fixed this. 

Thank you very much for the quick reaction :)

**Comment by koraktor** [comment]
Nice. :)
