### ISSUE TITLE
Bug - GameStats: Invalid profile fetch URL pattern

### ISSUE THREAD

**Issue by Rockz** [koraktor/steam-condenser#106]
Hello,

I'm using the API since this morning (thanks for great work ;) ) and identified an error (L90).

A 's' is missing in the profile URL pattern. Without correcting the pattern, an XML parsing occurs, since no XML data is responsed to the HTTP request:

--              url = "http://steamcommunity.com/profile/" + this.steamId64 + "/stats/" + this.gameName;
++              url = "http://steamcommunity.com/profiles/" + this.steamId64 + "/stats/" + this.gameName;

See you,
Rockz

**Comment by koraktor** [comment]
True, this should be fixed.

Additionally, the PHP implementation lacks the ability to handle numeric SteamIDs at all.
