### ISSUE TITLE
Play time for games without stats

### ISSUE THREAD

**Issue by Nevon** [koraktor/steam-condenser#113]
This is more of a question than an issue, but for some reason I can't seem to access the stats for games that don't have a friendly name, despite the fact that SteamId->getGameStats seems to indicate that I should be able to fetch the stats for any games in SteamId->games.

Maybe I'm doing something wrong:

```
public function getGameStatsById($steamid) {
    $playerobj = new SteamId($steamid);

    $res = $playerobj->getGames();

    foreach ($res as $key => $val) {
        $stats = $playerobj->getGameStats($key);
        print $key . ': ' . $stats->hoursPlayed;
    }
}
```

It comes back with the SteamCondenserException with message 'Stats for game blah blah do not exist'. But as I'm getting the game name straight from SteamId->getGames, I don't see how that's possible. I'm aware I may not be able to get stats on achievements for all games, but hoursPlayed should be available.

**Comment by koraktor** [comment]
`SteamId#getGames()` returns a array where the keys are the human-friendly names and the values are the friendly names (or false if the game doesn't have stats.

So your code should look like:

``` php
public function getGameStatsById($steamid) {
    $playerobj = new SteamId($steamid);

    $res = $playerobj->getGames();

    foreach ($res as $key => $val) {
        if($val !== false) {
            $stats = $playerobj->getGameStats($val);
            print $key . ': ' . $stats->hoursPlayed;
        }
    }
}
```

**Comment by Nevon** [comment]
Yes, I did that at first, but then I only get stats for the games that have friendly names. Are all the stats unavailable for those games? If I go to my steam id page, I can see that, for example, I've played GTA IV: Episodes from Liberty City for 17.4 hours. GTA doesn't have a friendly name, so I can't get that information via steam condenser.

**Comment by koraktor** [comment]
Yes, only games with stats have so called friendly names (because it's used in the stats URL).

But I see that Valve has changed the games listing of player to include the play time. Though, there's no implementation in Steam Condenser to retrieve that data, yet.

**Comment by Nevon** [comment]
I see. Thank you for your swift reply!

**Comment by koraktor** [comment]
I reopened this issue (and changed the subject) as I plan to add this in the future.
