### ISSUE TITLE
Add notices for received packets

### ISSUE THREAD

**Issue by timmw** [koraktor/steam-condenser#116]
When I query a master server I get lots of notices telling me a packet has been sent but not when received. It would be good if there were notices for received packets and perhaps when a packet is sent but there's no response. Also perhaps a report of how many packets were sent / received / lost during the request.

**Comment by koraktor** [comment]
This is more or less related to #18.

I'd like to improve logging before releasing 1.0.0 – probably the last big change before the release. I'd like to add more debugging output as well as a more simple way of disabling it.

**Comment by timmw** [comment]
Sounds good. It would also be good if the the servers were available as the packets arrive from the master servers. At the moment if I query the master servers with the default $retries = 3 and $timeout = 1000 I get a timeout exception every time.

**Comment by koraktor** [comment]
That's a whole other story. Thanks to your suggestion, users can now [try to overcome](https://github.com/koraktor/steam-condenser/commit/097c597f7851f3a4a52f7bc937bcb6f33574e65e) the connectivity problems of the master servers. But this isn't related to logging and additionally I fear we can't do anything more to fix it.

**Comment by timmw** [comment]
Would it be possible to return the server array even if there is a timeout with some kind of message to say not all servers were returned?

**Comment by koraktor** [comment]
Yes, sounds reasonable.

But please do not misuse issues for different topics. Don't be afraid to open new ones. I did add one for this question: #118.

**Comment by timmw** [comment]
Oops, my phone is a nightmare, sorry for double post. I'll create new issues for new issues in future :)

**Comment by koraktor** [comment]
Finally added some additional logging output to master server queries.
