### ISSUE TITLE
Number of players and max players in wrong order

### ISSUE THREAD

**Issue by timmw** [koraktor/steam-condenser#117]
When using GoldSrcServer->getInfo() max players and numbers of players are in the wrong order, eg.

[maxPlayers] => 0
[numberOfPlayers] => 22

https://github.com/koraktor/steam-condenser/blob/master/php/lib/steam/packets/S2A_INFO2_Packet.php#L41

Numbers of players should come before max players.

**Comment by koraktor** [comment]
Thanks, wonder why this never striked someone.
