### ISSUE TITLE
JSONObject["item_slot"] not found

### ISSUE THREAD

**Issue by extremo** [koraktor/steam-condenser#121]
Hi,

I was trying the java implementation today. tried to get items from team fortress 2 inventory and found the following bug:

At the moment all items with no item slot get ignored (disappearing in nirvana through catch block in 0.14.1).
I tracked it down to the following exception though: JSONObject["item_slot"] not found

Just tried with 1.0.0 and same bug seems to exist in this version (but exception gettin printed to console now):
com.github.koraktor.steamcondenser.exceptions.WebApiException 
-> Would be cool if you could add some additional information in these log messages 

Downloaded the 1.0.0 sources and tried to test with it but couldnt get it to work till now. Will give it a look tomorrow ;) 

Thanks for your work on this project and greetings
Andreas

**Comment by koraktor** [comment]
I didn't know such items even existed and I never encountered one of them during my tests. Do you have an example item / account this happens for?

**Comment by extremo** [comment]
I tested with this steamId: http://steamcommunity.com/profiles/76561198042871210
Affected items I noticed are crates, metals, keys, nametags, colors

For the exceptions: i think was wrong in my original message: theres just another exception thrown in 1.0.0 then in 0.1.4. The exception in 0.1.4 was more precise than the one in 1.0.0 though. Only got them printed out with my test method.

**Comment by koraktor** [comment]
Thanks. I'm about to fix this right now - it's a Java specific problem. Maybe that's why I didn't encounter it yet.

BTW: The `WebApiException` thrown because of this problem holds the `JSONException` thrown by `JSONObject#getString()` as its cause. So I think this is enough information.

**Comment by extremo** [comment]
Thanks for fixing it that fast :)
