### ISSUE TITLE
Ruby gem (1.0.0) will not install properly, creates empty dir

### ISSUE THREAD

**Issue by jschuur** [koraktor/steam-condenser#122]
Attempting an install via `gem install steam-condenser` simply creates an empty steam-condenser-1.0.0 directory in my gems directory. I've replicated this across 2 local development instances (Macs) and one production system (Ubuntu), all of them using RVM.

I was able to clone the entire repo and manually copy the ruby files into the empty directory, and then the Ruby gem worked.

Maybe this is related to the current issue #120?

**Comment by koraktor** [comment]
I'll have to check that. Can't think of anything that could have caused this. The release script stopped working right before 1.0.0 (see #120), but that shouldn't be a problem. I just called `rake gem` manually.

**Comment by jschuur** [comment]
Confirmed that it installed properly now in 1.0.1 on a machine that previously had a problem with 1.0.0.

Thanks for the speedy fix!

**Comment by koraktor** [comment]
Thanks for reporting all those issues, and even better confirming the fix. :+1:
