### ISSUE TITLE
How to reference the WebApi?

### ISSUE THREAD

**Issue by jschuur** [koraktor/steam-condenser#126]
I've read the class and instance methods for the WebApi in the docs, but I can't quite figure out how to use it in Ruby. Do I call SteamCondenser::WebApi?

Could you provide the proper way in Ruby to initialize the WebAPI, set the API key and then call `json!('ISteamUser', 'GetPlayerSummaries', 'v0002', 'steamids=76561197960779568,76561197972606228,76561197960542185')`?

It wasn't clear from the docs how to do that.

**Comment by koraktor** [comment]
It's pretty easy although I admit this might be clearer in the docs.

This should do the trick:

``` ruby
WebApi.api_key = YOUR_API_KEY
WebApi.json! 'ISteamUser', 'GetPlayerSummaries', 2, { :steamids => '76561197960779568,76561197972606228,76561197960542185' }
```

**Comment by jschuur** [comment]
Thanks again for pointing that out. I could have sworn I tried it that way, but probably left out the _ from api_key.

I'm still having a problem with the `json!` variant, as opposed to just the `json` call. I get the following error:

```
ruby-1.9.2-p290 :003 > f = WebApi.json! 'ISteamUser', 'GetPlayerSummaries', 2, { :steamids => '76561197960779568,76561197972606228,76561197960542185' }
NoMethodError: undefined method `[]' for nil:NilClass
    from /Users/jschuur/.rvm/gems/ruby-1.9.2-p290/gems/steam-condenser-1.0.1/lib/steam/community/web_api.rb:72:in `json!'
    from (irb):3
    from /Users/jschuur/.rvm/rubies/ruby-1.9.2-p290/bin/irb:16:in `<main>'
```
