### ISSUE TITLE
bad practice catching timeout exception internally

### ISSUE THREAD

**Issue by kruvas** [koraktor/steam-condenser#127]
hey! i try to use steam condeser, but found some issue, wich cost me about a half day to investigate problem

situation: server is restarting (down and up) and immediatly after that script try to reread players

but server starting not in a moment, so sometimes steam-condenser not receive answer in timeout.
and it show this by E_USER_NOTICE 
Expected S2A_PLAYER_Packet, but timed out. The server is probably offline.
BUT! GameServer::handleResponseForRequest catch timeout exception

```
    } catch(TimeoutException $e) {
        trigger_error("Expected {$expectedResponse}, but timed out. The server is probably offline.");
    }
```

and other logic continue work for next steps in algo, which leeds to mistakes, which too hard debug, because it happened in only rare timeout related period

after catching timeout exception script continue work in same object, same connection. i think that need to drop this connection and start another, or not catch timeout exception for handling it properly in external logic

its look like this
Sending packet of type "A2S_PLAYER_Packet"
Expected S2A_PLAYER_Packet, but timed out. The server is probably offline.

Sending packet of type "RCONGoldSrcRequest"
Received packet of type "RCONGoldSrcResponse"

Sending packet of type "RCONGoldSrcRequest"
Sending packet of type "RCONGoldSrcRequest"
Received packet of type "S2C_CHALLENGE_Packet"

and finally crashed
Fatal error:  Call to undefined method S2C_CHALLENGE_Packet::getResponse() in /steam-condenser/steam/sockets/GoldSrcSocket.php

because of this bug, i cant use this library, it crashed my script unpredictable which is unacceptable. i see a lot of work made to create this lib, but also see that library need to be revised in more up-to-day standarts - add normal logging, not via user_notice, revised work with exception, more control on current state in internal functions (for example  in updatePlayers in begining check for challenge number, and try to get new one, if inexistance. but after getting new one (wich may end with timeout/error) nothing checked and etc, etc... hope its be done and justify a large change of version number )))
thanks for attention

**Comment by koraktor** [comment]
I must admit you're totally right. This is bad practice.

The internal timeout handling was added after a protocol change (or a bug) in dedicated servers very early in the development of Steam Condenser. It seems I missed to revise this section as I'm pretty sure this isn't needed any more.

The other things you pointed out may get some attention in the future. But I don't think e.g. external logging is really a must-have.

**Comment by kruvas** [comment]
> I'm pretty sure this isn't needed any more.

really? how about hardly catching crash Fatal error: Call to undefined method S2C_CHALLENGE_Packet::getResponse() in /steam-condenser/steam/sockets/GoldSrcSocket.php
it is small bug in your opinion? :) this is not serious.

best thing in your library - huge low level work with valve protocol, covered almost all it feature.
bad thing in your library - poorly written high level library function (read players, etc) it misses the correct handling error conditions. that need to be improved and/or rewritten, i think.

> But I don't think e.g. external logging is really a must-have.

for this such feature-rich library it really "must-have". implementing library not so easy... sadly now it not work as "hummer" - it requires fine tuning and adjustment (debugging) for correct work. good readable log really help.
and once time you implement user notice for debugging - so it is means that before it was necessary. i think since that time nothing changed.
for first time just replace user notice whith write to log array/object

cheers!

**Comment by koraktor** [comment]
`Fatal error: Call to undefined method S2C_CHALLENGE_Packet::getResponse()` is caused by the internal timeout handling, although this never happened to me during tests and may be a special case. This isn't a small bug, but the main reason is somewhere else - i.e. timeouts.

I know there's a lot of work that can be done to improve the overall user experience (this includes logging and so on). But this isn't a one-line patch, so it requires some time. The reason why the library works the way it does now is that it's mainly a object-oriented wrapper around the low-level protocol with some added functionality. It's not that high-level, yet.

**Comment by kruvas** [comment]
> is caused by the internal timeout handling

as i can see (but not look deeper - lib is huge now for me) this is an indirect cause. may be crash reason is wrong algo in hadling answers to requests in unpredictable formats? ie expect RCONGoldSrcRequest, but recieve S2C_CHALLENGE_Packet but try to handling as RCONGoldSrcResponse? but sorry, you certanly much better know your work :)

> although this never happened to me during tests and may be a special case. This isn't a small bug, but the main reason is somewhere else - i.e. timeouts.

yeah, it is special case. that is why i so struggling to catch it (press F5 about 10-20 times to reproduce)
as i can see for reproduce bug need to
1) timeout in thirst request A2S_PLAYER_Packet (server down)
2) normal work for next requests (server up)
ie between step 1 and 2 server begin answer to requests.
chance for this too small, but consequences are very serious - crashing apps :)
but if think that can happining not only when server starting, but also when network connection is instable, or game server is overloading and drop/misses some network packets

**Comment by koraktor** [comment]
Internal catching of `TimeoutException` in `GameServer#handleResponseForRequest()` has been removed.

Improved logging will hopefully make it into one of the next versions.
