### ISSUE TITLE
Unittests are falling and taking forever

### ISSUE THREAD

**Issue by gutomaia** [koraktor/steam-condenser#137]
Those tests are supposed to be simple and pretty fast. I've already done some tests with mocks. I will try to mock and make the other tests more controlled, in the future. However, for now, most of the are falling.

Results :

Tests in error: 
  groupByCustomUrl(com.github.koraktor.steamcondenser.steam.community.SteamCommunityTest)
  groupByGroupId64(com.github.koraktor.steamcondenser.steam.community.SteamCommunityTest)
  rconLongGoldSrcServer(com.github.koraktor.steamcondenser.RCONTest)
  rconLongSourceServer(com.github.koraktor.steamcondenser.RCONTest)
  rconShortGoldSrcServer(com.github.koraktor.steamcondenser.RCONTest)
  rconShortSourceServer(com.github.koraktor.steamcondenser.RCONTest)
  invalidGoldSrcServer(com.github.koraktor.steamcondenser.QueryTest)
  invalidSourceServer(com.github.koraktor.steamcondenser.QueryTest)
  randomGoldSrcServer(com.github.koraktor.steamcondenser.QueryTest)
  randomSourceServer(com.github.koraktor.steamcondenser.QueryTest)

Tests run: 17, Failures: 0, Errors: 10, Skipped: 0

**Comment by koraktor** [comment]
I'm aware of that problem. Testing wasn't really in my focus up until a few weeks ago. I already revised the Ruby tests and I'd like to do the same with the Java and PHP tests.

**Comment by gutomaia** [comment]
I belive that I can review the Java tests and @klaussilveira could review PHP tests.

I will comment some stuff and put in a TODO on some of them. I will make them all ok with the same couverage level.

I have the intention to Erase the SteamComunityTest in order to substitue with my own test in a near future.

**Comment by snkinard** [comment]
What's the latest status on the mocks for the Java implementation?

**Comment by koraktor** [comment]
The [`xml-helper` branch](https://github.com/koraktor/steam-condenser-java/tree/xml-helper) already adds a few tests using mocks and is [green on Travis CI](http://travis-ci.org/#!/koraktor/steam-condenser-java/branch_summary). There are still some tests missing for sockets and servers before it can be merged into / rebased on `master`.

**Comment by koraktor** [comment]
Finally. This is now done.

http://travis-ci.org/#!/koraktor/steam-condenser-java/builds/1083658

**Comment by snkinard** [comment]
Awesome! This will be very helpful
