### ISSUE TITLE
Add more Steam Games

### ISSUE THREAD

**Issue by HunterJoe** [koraktor/steam-condenser#138]
I was hoping you could get around to adding more Steam Games. I play a free steam game called America's Army 3 and was hoping to use this package to create all kinds of cool stuff for it but it doesn't seem to work with with it. 

AA3 is not a Source Engine Game, but an Unreal Engine Game that is free on Steam. With the most recent patch they moved from a third party stat tracking system to full Steam integration. The only thing I can use this for is to query the steam community, not the servers. So if you could work that in it would be much appreciated.

**Comment by koraktor** [comment]
Implementing one or more additional query protocols is a pretty big task. I'm happy that the two other protocols are working without flaws. If anyone wants to contribute an additional protocol, I'd be happy to add it to the library. But right now, I don't have the time to do that myself.

**Comment by Schteven** [comment]
Hi, any news on this thread? i'm looking forward to have some tools for AA3

**Comment by koraktor** [comment]
No, sorry. Like said before, this is a major task that AFAIK requires a completely new protocol to be implemented. To be honest, I don't believe this will make it into Steam Condenser if there's no volunteer providing at least one implementation for such a protocol.

**Comment by Schteven** [comment]
Oh too bad, i wish i could do it but i have no idea how

**Comment by Yeggstry** [comment]
You'll have to be a bit more specific as to what server information you are trying to get from AA3.

As part of the [ISteamApps](koraktor/steam-condenser/issues/197) implementation you will be able to use the WebApi to see the servers at a particular address, as per this [example](http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001/?addr=38.113.114.40)

However, this only provides limited details, I can't see a call in the WebApi that allows a list of servers for a particular game to be retrieved, or an AA3 api to do the same.

**Comment by koraktor** [comment]
@Yeggstry Does this work for non-Valve games, too? However, I don't think this is enough for all but the very simplest use cases.

@iKyvill @HunterJoe Depending on your environment, you may want tro try libraries like [GameQ](https://github.com/Austinb/GameQ) (PHP) with more supported protocols (but less functionality).

**Comment by Schteven** [comment]
Those steam api's arent realy clear to me, but it looks interesting.
What i would like to do is build a website for my AA3 server and get all the info out of it, like playerstats (score, kills, kia, roe, etc)
So i can build my own database of players, just for my server.

I tried the GameQ, but since AA3 updated from 3.2 to 3.3 it doesn't work anymore and since the last update of GameQ was in 2011, i don't suspect anything new to come.

**Comment by Yeggstry** [comment]
@koraktor I haven't tested any other non-Valve games. I would guess that there would have to be _some_ SteamWorks integration in order for it to appear in this operation.

It actually looks like there are [some operations](https://partner.steamgames.com/documentation/) which SteamWorks games can use to query a list of games, but this isn't exposed through the WebApi. If I were Valve I'm not sure I'd want to either :)

**Comment by HunterJoe** [comment]
I did manage to use Steam Condenser to build something for AA3. It's not exactly what I had in mind when I started out building it, but it does work.

you can see it [here](http://www.25idtacops.com/stats/). The only issue I have with it is retrieving the list of friends initially. If you have a lot of friends, it can take long time. Anyway, check it out and let me know what you all think.

**Comment by Schteven** [comment]
@HunterJoe It looks cool if i want to develop my idea a little bit further to a community, i only want to query a gameserver to get the playerstats, but this can be usefull too. keep up the good work! 

I just found out that GameQ is actually working with AA3.3 and comes close to what i had in mind.

**Comment by HunterJoe** [comment]
@iKyvill you will probably find that the stats reported by the server are fairly useless. Reason being is the game was never really developed to report server stats after they left Pragmatic. The system Pragmatic had in place would report server stats, but it was not accurate all the time. Once they dropped Prag and went to Steam, server stats were pretty much non-existent AFAIK, outside of player names, score and time on server, the info reported in the Steam server browser. If that is all you are looking for then you should be ok, but other than that, use the Steam API to get player stats, much like my app does.

**Comment by Yeggstry** [comment]
I'm guessing you use ISteamUserStats/GetUserStatsForGame for the stats @HunterJoe ? I just checked it and it provides a good amount of individual stats :)

**Comment by HunterJoe** [comment]
@Yeggstry No. I use Steam Condenser, not the Web API from Steam.

**Comment by Yeggstry** [comment]
Fair enough :) Soon you'll be able to use both ;)

**Comment by koraktor** [comment]
Finally closing this for good. I don't see a chance of any new protocol making it into Steam Condenser.
