### ISSUE TITLE
Community Message

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#140]
The lib should provide the ability to send a message (as possible when browsing Steam community) to a Steam ID.

**Comment by koraktor** [comment]
I like the idea, but I'm afraid this isn't possible at the moment.
First, there is no API to access/send messages. And additionally Steam Condenser doesn't feature any authentication with the Steam Community yet (aside from the Web API, but that's a different story).

I'll keep an eye on this, though.

**Comment by koraktor** [comment]
Just to get this right. There is OAuth authentication now, but still no API for messaging.

**Comment by koraktor** [comment]
It seems Valve will not add an API for this any time soon.
