### ISSUE TITLE
Improve Steam group fetching

### ISSUE THREAD

**Issue by koraktor** [koraktor/steam-condenser#142]
The way `SteamGroup`s are fetched right now is pretty dumb. A whole page of members needs to be fetched if you only want to load the member count, but the members are discarded.

When fetching the member count this first page of members (most groups will probably only have one page) should be stored as member objects (i.e. `SteamId`s) and the group should be marked as "partially fetched". After that fetching all members should either don't need to fetch anything (for groups with only one page) or only fetch the remaining pages.

I already started working on this in the Ruby implementation.

**Comment by snkinard** [comment]
I'd like to confirm that there is no work to be done for this in the Java implementation. 

From the documentation for _SteamGroup.getMemberCount()_: 
"If the members have already been fetched the size of the member array is returned. Otherwise the group size is separately fetched without needing multiple requests for big groups."

**Comment by koraktor** [comment]
That's not what I aim for in this issue.

The problem with the current implementation is that it discards the first page of members if you only call `SteamGroup#getMemberCount()`. This way it is wasting requests.

**Comment by snkinard** [comment]
Thanks for the clarification!

If no one has started work on the Java Implementation I'd like to investigate and propose a solution.

**Comment by koraktor** [comment]
If you're familiar with Ruby's syntax, you may have a look at commit [98a895e4](https://github.com/koraktor/steam-condenser-ruby/commit/98a895e4e36fa47d2a10319a0094a49b93e0f5f5) in the Ruby repository. It already implements an optimization.
Thanks anyway.

**Comment by snkinard** [comment]
No problem. Are you planning on implementing this optimization in Java yourself? If you need someone to take on that task I can volunteer.

**Comment by koraktor** [comment]
I'd do this for Java, too. If you're faster, feel free to do so. I'm happy for every new contributor.

**Comment by koraktor** [comment]
Ok, PHP implementation is still missing. I'm going to get this done soon. I want to have 1.2.0 ready.

**Comment by koraktor** [comment]
Done.
