### ISSUE TITLE
Could not read from socket

### ISSUE THREAD

**Issue by riemers** [koraktor/steam-condenser#143]
I dont know if this is a condenser issue or not (otherwise close it) but i am getting frequent:

```
Fatal error: Uncaught exception 'Exception' with message 'Could not read from socket.' in /home/lethal/public_html/admin/steam-condenser/lib/Socket.php:109
Stack trace:
#0 /home/lethal/public_html/admin/steam-condenser/lib/steam/sockets/SteamSocket.php(113): Socket->recv(1500)
#1 /home/lethal/public_html/admin/steam-condenser/lib/steam/sockets/MasterServerSocket.php(30): SteamSocket->receivePacket(1500)
#2 /home/lethal/public_html/admin/steam-condenser/lib/steam/servers/MasterServer.php(125): MasterServerSocket->getReply()
#3 /home/lethal/public_html/admin/servers.php(82): MasterServer->getChallenge()
#4 /home/lethal/public_html/admin/servers.php(436): checkversion()
#5 {main}
  thrown in /home/lethal/public_html/admin/steam-condenser/lib/Socket.php on line 109
```

If i run the same script again, it goes ok. Run it again and it breaks "maybe"

Looks like the servers from valve might be acting up, but just checking to be sure because it halts my php script.

**Comment by koraktor** [comment]
This error might have various reasons, especially as the master servers are under heavy load and might drop packets etc. The best would be to surround your calls to Steam Condenser with a try-catch-block to catch the exception and handle it gracefully.

**Comment by riemers** [comment]
is there a example call that when it fails, retry it for example 3 times then fail?

**Comment by koraktor** [comment]
The `MasterServer` class does this by design, but a bit differently. It checks each IP address (that's assigned to the master server's name, e.g. hl2master.steampowered.com) and fails if all fail.

If you want it like you described try this:

``` php
<?php
$attempt = 1;
while(true) {
    try {
        someCallThatMayFail();
        echo "Success in attempt $attempt!";
        break;
    } catch(Exception $e) {
        echo "Attempt #$attempt failed!";
        $attempt ++;
        if($attempt > 3) {
            echo 'Ultimately failed!';
            break;
        }
    }
}
```

**Comment by riemers** [comment]
Good one, i'll use that in the future too for my calls (since i dont want it to break up the rest) but it would be better for me to split up my servers.php (web/crontab/display) far in the future to do list.
