### ISSUE TITLE
Access more data returned by API calls

### ISSUE THREAD

**Issue by snkinard** [koraktor/steam-condenser#146]
While playing around with the java implementation for Team Fortress 2 I noticed that there are a few places where relevant data returned by an API call isn't being consumed. For Example:

_GameAchievement_
- iconClosed
- iconOpen

_SteamGame_
- gameIcon
- gameLogo

_TF2Spy_
- iheadshots

example api call: http://steamcommunity.com/id/n00bosaurus_rex/stats/tf2?xml=all

I haven't looked into this extensively yet. This is not an exhaustive list of all cases. If we want to move forward with this I can find all cases and implement for java.

**Comment by koraktor** [comment]
Sure, I'm always happy when missing (or changed) parts of the XML data can be added to Steam Condenser.

**Comment by snkinard** [comment]
In cases where a percentage is available from the xml, do you still prefer to calculate the percentage in the code?

For example, in _AbstractL4DStats.java_  you have: 

``` java
this.versusStats.put("finalesSurvivedPercentage", (Integer) this.versusStats.get("finalesSurvived") / (Integer) this.versusStats.get("gamesPlayed"));
```

But _finalespct_ is available in the xml so you could do this:

``` java
this.versusStats.put("finalesSurvivedPercentage", Integer.parseInt(versusStatsElement.getElementsByTagName("finalespct").item(0).getTextContent()));
```

**Comment by koraktor** [comment]
I think this would require a bit of benchmarking. I'd guess reading the XML data requires a bit more time than doing a simple calculation with existing data.

Apart from that it should be:

``` java
this.versusStats.put("finalesSurvivedPercentage", Float.parseFloat(versusStatsElement.getElementsByTagName("finalespct").item(0).getTextContent()));
```

**Comment by koraktor** [comment]
Forgot to mention that this is now done for Java and Ruby. The latter is missing some code for `SteamGame` though. PHP is still missing.

**Comment by koraktor** [comment]
PHP is done now, too.
