### ISSUE TITLE
fd leak on linux systems

### ISSUE THREAD

**Issue by schnix1980** [koraktor/steam-condenser#148]
class "SteamSocket.java", method “receivePacket(int bufferLength)”

the selector "selector" gets opened and closed, if the destination server is alive and responding. But if the IOException gets thrown, the selector remains opened. This behavior causes a file descriptor leak on linux systems, because additional "pipes" and "anon_inodes" remain after each query in /proc/<PID>/fd. The number of those file descriptors is limited to 1024 by default.

You could fix it by adding “selector.close();” to the “finally” section after the catch clause or something like that.

Regards

**Comment by koraktor** [comment]
Good find. Thanks for reporting.

**Comment by koraktor** [comment]
This should do it, thanks again.
