### ISSUE TITLE
GoldSrc (+L4D2) does not support A2S_SERVERQUERY_GETCHALLENGE

### ISSUE THREAD

**Issue by massl** [koraktor/steam-condenser#150]
I wondered why initialize() fails on GoldSource servers and found out that it's because of the method updateChallengeNumber() that is not supported by GoldSource and L4D2 servers.

See https://developer.valvesoftware.com/wiki/Server_queries#A2S_SERVERQUERY_GETCHALLENGE
and
https://developer.valvesoftware.com/wiki/Talk:Server_Queries#A2S_SERVERQUERY_GETCHALLENGE_not_working_since_last_HLDS_update
reported by Koraktor ;)

WIll this be fixed for the steam-condenser? I'm using the PHP version.

**Comment by koraktor** [comment]
This should definitely be fixed.

To be honest, I just forgot to update the code. And it seems a lot of people weren't using `updateChallengeNumber()` or `initialize()` at all. If you don't use them, you'll be fine.

**Comment by massl** [comment]
Not using initialize() is what I'm doing now. I just wanted to inform you about it :) Thanks!

**Comment by koraktor** [comment]
Fixed.
