### ISSUE TITLE
Incorrect Element name in AbstractL4DStats

### ISSUE THREAD

**Issue by snkinard** [koraktor/steam-condenser#151]
Apologies if you already fixed this. I wanted to bring this to your attention quickly before the next release. In AbstractL4DStats.java an incorrect element names are used in two places.

this.teamplayStats.put("avgProtected", Float.parseFloat(teamplayStatsElement.getElementsByTagName("avgProtected").item(0).getTextContent()));

this.teamplayStats.put("avgWasProtected", Float.parseFloat(teamplayStatsElement.getElementsByTagName("avgWasProtected").item(0).getTextContent()));

'avgProtected' should be 'protectedavg'
'avgWasProtected' should be 'wasprotectedavg'

**Comment by koraktor** [comment]
Good find, thanks. Didn't fix it yet.

**Comment by snkinard** [comment]
FYI I won't be doing a pull request with the fix. I assume you can implement it on your own easily enough :)
