### ISSUE TITLE
hoursPlayed() showing wrong value

### ISSUE THREAD

**Issue by Archey6** [koraktor/steam-condenser#155]
I was playing around with steam condenser, I used this code to get the hours played for tf2

http://pastebin.com/7ux3hPpD (had to put it in pastebin, posting in here wasn't working correctly)

but when dumping the variable it seems to be showing the hours played in the last two weeks, when trying with other games like l4d, and l4d2 it didn't change, it stayed around 98, it should be displaying atleast 700(my total hours on tf2)

**Comment by koraktor** [comment]
The `hoursPlayed` attribute of `GameStats` objects only includes the last two weeks, so this behavior is totally fine. You're probably looking for the value of `secondsPlayedAllClassesLifetime`, see http://steamcommunity.com/id/Archey6/stats/tf2?xml=all.

I didn't add this yet, but I will do shortly. Thanks for the reminder.

**Comment by Archey6** [comment]
Yeah that true, I found the function i was looking for `getTotalPlaytime();` but alas I have no idea how to utilize it because I'm terrible at OOP

**Comment by koraktor** [comment]
I just added `TF2Stats#getTotalPlaytime()`.

In fact, you may be looking for another value. Try using this instead:

``` php
<?php
$id = new SteamId('Archey6');
var_dump($id->getTotalPlaytime('tf2'));
```

This works for all games and will return the time (in minutes) the user has played this game (i.e. the game was running). `TF2Stats#getTotalPlaytime` only includes the time the player was really active (i.e. "alife").
