### ISSUE TITLE
testFetchMembers(); returning error

### ISSUE THREAD

**Issue by Archey6** [koraktor/steam-condenser#156]
I ran this code

`
$data = new SimpleXMLElement(getFixture('valve-members.xml'));
        $mockBuilder = $this->getMockBuilder('SteamGroup');
        $mockBuilder->setConstructorArgs(array('valve', false));
        $mockBuilder->setMethods(array('getData'));
        $group = $mockBuilder->getMock();
        $group->expects($this->once())->method('getData')->with('http://steamcommunity.com/groups/valve/memberslistxml?p=1')->will($this->returnValue($data));
        $group->fetchMembers();
        $groupMembers = $group->getMembers();
        $this->assertEquals('103582791429521412', $group->getGroupId64());
        $this->assertEquals('76561197960265740', $groupMembers[0]->getSteamId64());
        $this->assertFalse($groupMembers[0]->isFetched());
        $this->assertEquals('76561197970323416', $groupMembers[sizeof($groupMembers) - 1]->getSteamId64());
        $this->assertTrue($group->isFetched());`

and got this error

`Call to undefined function getFixture()`

**Comment by koraktor** [comment]
You have to run the tests like this:

``` bash
$ phpunit --bootstrap tests/bootstrap.php tests/
```
