### ISSUE TITLE
Steam Condenser last SRCDS update

### ISSUE THREAD

**Issue by f1nality** [koraktor/steam-condenser#160]
Hello!
After last Valve SRCDS update my php web script stopped working, giving RCONNoAuthException.
Can you give any comments please? And will this be fixed?

Thanks in advance

**Comment by koraktor** [comment]
The last update of SrcDS reenabled IP bans for RCON, so this might be the cause, although the exception should be `RCONBanException` then. Could you check that your IP isn't banned on the game server(s)?

**Comment by f1nality** [comment]
Ban should be in banned_ip.cfg? If so, there is no ban.
I have tried from different IP and it also gives me 
exception 'RCONNoAuthException' with message 'Not authenticated yet.' in SourceServer.php:117 Stack trace: #0 tt.php(7): SourceServer->rconExec('status') #1 {main}

Could you confirm that Steam Condeser's RCON works on current version?

**Comment by f1nality** [comment]
Oups, I'm sorry. The problem is not related to steam-condenser.
It was because of broken sourcemod plugin. Valve have changed some offsets.
steam-condenser works fine.

**Comment by koraktor** [comment]
Great, thanks for letting me know.
