### ISSUE TITLE
Better support for inventories

### ISSUE THREAD

**Issue by koraktor** [koraktor/steam-condenser#162]
The current implementation of game inventories is pretty simple. It should provide better support for accessing item attributes, item sets, qualities, levels and so on.

**Comment by ghoeffner** [comment]
Definitively need that!
Kinda the only thing the lib lacks off.

**Comment by koraktor** [comment]
@ideal-hosting You're using the Ruby gem, right? Maybe you want to have a look at the new code.

**Comment by koraktor** [comment]
With the bunch of latest changes to inventories I guess this can be closed.
