### ISSUE TITLE
Problem parsing gaming URL due to steam "malformed" url

### ISSUE THREAD

**Issue by sikora** [koraktor/steam-condenser#163]
I found out that steam gamelink url, for specific games, is comming with double slashes and this is braking the parter in game_stats.rb

I did a small change in my local lib as a work around and I believe it can be applied without big concerns.

this is the original parsing regexp:
@app_id       = @xml_data.elements['game/gameLink'].text.match(/http:\/\/store.steampowered.com\/app\/([1-9][0-9]+)/)[1].to_i

change to:
@app_id       = @xml_data.elements['game/gameLink'].text.match(/http:\/\/store.steampowered.com\/+app\/+([1-9][0-9]+)/)[1].to_i

just added the plus sign to make it work with http://store.steampowered.com//app//48000  url like

Didn't want to bother with a fork for such small work around.

Best regards.

**Comment by koraktor** [comment]
Thanks for the hint, this has been fixed in the commits mentioned above.
