### ISSUE TITLE
Trading support

### ISSUE THREAD

**Issue by Philipp15b** [koraktor/steam-condenser#164]
Support for Steam Trading would be awesome.

**Comment by koraktor** [comment]
Sure thing, :ok_hand:

But currently, I'm not really involved into this. Is this currently possible only using the Web API?

**Comment by Philipp15b** [comment]
Yeah, it's only possible with the web api. There is a bot which implements this: 
https://github.com/Jessecar96/SteamBot/blob/master/SteamBot/TradeSystem.cs

**Comment by psychonic** [comment]
I'm fairly sure that it's not possible using only the web api, and that linked bot does not show differently.

Just as that bot does, you still need to initiate the trading session via Steam itself. The web api only works with an open trade session.

**Comment by Philipp15b** [comment]
Yeah, that's right, I forgot. You can only do it with [SteamKit](https://bitbucket.org/VoiDeD/steamre/overview) as far as I know. But it would be awesome for SteamKit users to have a good trading API though.

**Comment by koraktor** [comment]
Guess this won't be an option at the moment, then.

But I'll gladly add this, once it's supported for third party access.

**Comment by IamFive** [comment]
Hello, do u implement trade api? It's really very important for me.

**Comment by koraktor** [comment]
@IamFive Sorry, trading is still not available using public APIs.

**Comment by IamFive** [comment]
Hmm, I see, but SteamBot which implemented by C# got this feature. don't know how it works.

---

Best Regards!
Woo.Cupid 

## Im always here to assist you!

Skype: woo.cupid
Phone: +8615306980363
Email: iampurse@vip.qq.com
Addr : MinFa 5#608,XiaMen, Fujian, China 

From: Sebastian Staudt
Date: 2013-08-14 12:09
To: koraktor/steam-condenser
CC: woo
Subject: Re: [steam-condenser] Trading support (#164)
@IamFive Sorry, trading is still not available using public APIs.

**Comment by koraktor** [comment]
@IamFive This is done using SteamKit, see @Philipp15b's comment above.

**Comment by IamFive** [comment]
ok, thx for the reply. I will check steamkit's code later.

**Comment by josefcs** [comment]
Actually, steamkit is not required:

> Steam for Node.js
> This is a Node.js port of SteamKit2. It lets you interface with Steam without running an actual Steam client. Could be used to run an autonomous chat/trade bot.

URL: https://github.com/seishun/node-steam-trade

And

> Steam trading for Node.js
> Allows you to automate Steam trading in Node.js.

URL: https://github.com/seishun/node-steam-trade

**Comment by IamFive** [comment]
@JosefCS thx very much, i will check the node-steam-trade code.

i check the SteamKit's code, but it use socket to connection to steam and im not a .net coder, so it make me confused. 
I kindly checked node-js version, it seems it all use web request to finish the trade and i have implemented login through web yet, so i just need to know how it works.

**Comment by koraktor** [comment]
Loggin on (i.e. getting a session ID and cookie) uses the same procedure as SteamKit.

**Comment by koraktor** [comment]
There's still no easy way to do this using the documented APIs. So I'll close this for now.
