### ISSUE TITLE
Strict Standards and Error Reporting

### ISSUE THREAD

**Issue by dpi** [koraktor/steam-condenser#165]
In my environment, code must be valid under the strictest of standards at the latest version of PHP. Which means no debug code, or error messages printed to screen.

Instead of advising developers to lower error reporting threshold (koraktor/steam-condenser#159), why not rewrite portions of Steam Condenser to be strict, and PHP5.4, compatible?

This includes removing Socket->socket() and debug usage of trigger_error().

**Comment by koraktor** [comment]
Thanks for the hint. I know this is still an issue and I will finally take some time to get this right.

**Comment by dpi** [comment]
Would you accept patches/pulls to fix these issues? Or is something in the works?

**Comment by koraktor** [comment]
Oh sure. Especially as my available time to work on Steam Condenser is pretty limited right now.

**Comment by dpi** [comment]
What needs to be done here?

**Comment by koraktor** [comment]
Sorry of the delay. I'll have a look at it in the coming week or so.

**Comment by koraktor** [comment]
Some of the changes have been applied to the PHP version. Better logging will be part of version 2.
