### ISSUE TITLE
Store Prices API

### ISSUE THREAD

**Issue by Philipp15b** [koraktor/steam-condenser#166]
It would be nice if Steam Condenser included an API for the [store prices](http://wiki.teamfortress.com/wiki/WebAPI/GetAssetPrices) in TF2.

**Comment by koraktor** [comment]
This is on my list, but at a pretty low priority at the moment.

Pull requests are welcome, though.

**Comment by snkinard** [comment]
Is this being worked on right now? I am thinking about poking around with it over the holidays.

**Comment by koraktor** [comment]
It's been a long time, but no. I'm still trying to find some time to finalize 2.0.

So go ahead. I'm happy for any pull request.

**Comment by snkinard** [comment]
So I got started on this with that java implementation and made some decent progress. I recently started a new job and moved apartment so I've been derailed by all of that stuff. Some of the logic needs to be finished and it needs more tests: https://github.com/snkinard/steam-condenser-java/compare/issue-166

I hope to come back and finish it up as soon as I have time, but here's the branch if anyone else wants to pick up where I left off in the mean time: https://github.com/snkinard/steam-condenser-java/tree/issue-166

**Comment by koraktor** [comment]
It’s been a long time and I have to clean up old issues. This won’t make it into Steam Condenser as there’s no part of the library where this is really useful. You can still use the Web API code to query this interface and handle the reponse on your own.
