### ISSUE TITLE
Non-JPG images breaks the SteamGame java constructor

### ISSUE THREAD

**Issue by Unarmed** [koraktor/steam-condenser#167]
Some "games", such as the CS:GO SDK use gif images for their logos (or lack thereof). Trying to call the SteamGame constructor with such a game causes an exception since the logo hash Matcher on line 152 in SteamGame.java fails.

This, in turn causes calls such as fetchGames to fail entirely.

Offending image: http://media.steampowered.com/steamcommunity/public/images/avatars/33/338200c5d6c4d9bdcf6632642a2aeb591fb8a5c2.gif

Suggested fix: allow for more image types in regexp or ignore "No logo available"-images

**Comment by koraktor** [comment]
Thanks for the heads up.

Seems like Valve can't stick to a data format for much longer than a few months. :disappointed:

**Comment by Unarmed** [comment]
Yeah, i think it's just exceptions like the SDK - which really isn't a game at all that causes this. However, why limit your library to ust one type?

**Comment by koraktor** [comment]
Do you have a sample profile that includes this image?

**Comment by Unarmed** [comment]
Well, you could grab my profile http://steamcommunity.com/profiles/76561197960835008. Just try listing all games for that one and  the lib will throw exceptions.

**Comment by koraktor** [comment]
I fixed the problem using a slightly different approach.
The regex still only accepts the standard JPEG images, but it will fail gracefully for other URLs.

**Comment by Unarmed** [comment]
cool, how does that effect listGames? Will the list just be lacking those games then?

**Comment by koraktor** [comment]
No, the games are still available, but `getLogoUrl()` and `getLogoThumbnailUrl()` will return `null`.

**Comment by Unarmed** [comment]
Sweet. Thanks a bunch :)
