### ISSUE TITLE
baseURL for profiles specified with long gives wrong address

### ISSUE THREAD

**Issue by Unarmed** [koraktor/steam-condenser#168]
In method getBaseUrl(Object userId, Object gameId) in GameStats.java playerID is treated as if it is a Integer instead of a Long. This results in the wrong URL if a Long is supplied as a playerID. 

Line 94: if(userId instanceof Integer) {

Suggested fix, replace Integer with Long.

**Comment by koraktor** [comment]
Thanks for reporting.
