### ISSUE TITLE
Unable to get game stats

### ISSUE THREAD

**Issue by Marknel** [koraktor/steam-condenser#170]
Hi, so I followed the basic tutorial you outlined on the site homepage, however it fails.

The first line executes and gets the correct user information, however this line generates the following error code:

> stats = id.game_stats 'tf2'
> 
> NoMethodError: undefined method `[]' for nil:NilClass
>     from /Users/marknel/.rvm/gems/ruby-1.9.3-p194/gems/steam-condenser-? 1.2.1/lib/steam/community/game_stats.rb:112:in`initialize'
>     from /Users/marknel/.rvm/gems/ruby-1.9.3-p194/gems/steam-condenser-1.2.1/lib/steam/community/tf2/tf2_stats.rb:34:in `initialize'
>     from /Users/marknel/.rvm/gems/ruby-1.9.3-p194/gems/steam-condenser-1.2.1/lib/steam/community/game_stats.rb:89:in`new'
>     from /Users/marknel/.rvm/gems/ruby-1.9.3-p194/gems/steam-condenser-1.2.1/lib/steam/community/game_stats.rb:89:in `create_game_stats'
>     from /Users/marknel/.rvm/gems/ruby-1.9.3-p194/gems/steam-condenser-1.2.1/lib/steam/community/steam_id.rb:373:in`game_stats'
>     from (irb):23
>     from /Users/marknel/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.0/lib/rails/commands/console.rb:47:in `start'
>     from /Users/marknel/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.0/lib/rails/commands/console.rb:8:in`start'
>     from /Users/marknel/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.0/lib/rails/commands.rb:41:in `<top (required)>'
>     from script/rails:6:in`require'
>     from script/rails:6:in `<main>'

Hope this helps.

I'd love to use the service. What I really want to do is simply get a list of games that a user has played, and what their achievement completion % is. Any help is very much appreciated.

Thanks,
Mark.

**Comment by koraktor** [comment]
This was fixed in koraktor/steam-condenser-ruby@fa9c68fe06fbb66ed933066b8161241f9d2cacf0.

I should push out a new version, though. In the meantime, you might want to use the development code on the `master` branch.

**Comment by Marknel** [comment]
Many thanks. I'll work from the dev master branch.

Thanks for building this project. It's great.
