### ISSUE TITLE
JAVA: getTotalPlayTime fails with a SteamCondenserException if the target account has 1000 game hours or above.

### ISSUE THREAD

**Issue by Aerolite** [koraktor/steam-condenser#171]
Tracked it down in a debugger to line 401 in SteamId.java: "total = gameData.getFloat("hoursOnRecord");"
The reason this fails is because Steam inserts a comma (,) in the number to group the digits (eg. 1,684.7), and getFloat has a panic attack. See here for an example: http://steamcommunity.com/id/Snarbles/games?xml=1
Should be a simple fix. :)

**Comment by koraktor** [comment]
Fixed. Thanks for reporting.
