### ISSUE TITLE
Clean namespacing for the PHP library

### ISSUE THREAD

**Issue by koraktor** [koraktor/steam-condenser#172]
This will raise the minimum required PHP version to 5.3. Guess this shouldn't be a problem once version 2.0.0 will be released. Hopefully in early 2013.

**Comment by nils-werner** [comment]
Also, you should aim to support PSR-0 so that the classes can be autoloaded properly. See [this related discussion on SO](http://stackoverflow.com/questions/17195044/composer-not-auto-loading-package?utm_source=laravel).

**Comment by koraktor** [comment]
@nils-werner :+1:

**Comment by koraktor** [comment]
Finally making progress on this one. See the [`psr-0`](https://github.com/koraktor/steam-condenser-php/tree/psr-0) branch.
