### ISSUE TITLE
[ruby] Game Play Statistics being shared across users

### ISSUE THREAD

**Issue by Marknel** [koraktor/steam-condenser#173]
So I've been seeing some very odd behaviour and while it's difficult to replicate, I believe I have tracked it down. I'm using the gem direct from GitHub (master)

Essentially my system takes a users's game history from Steam and stores it.

I have import code that looks as follows:

```
# Clearing the cache to try and prevent importing games not owned by this user
SteamId.clear_cache()
id = SteamId.new steam_username
SteamId.clear_cache()

# For each of the games associated with the user's Steam account find the relevant game in this system
id.games.each do |steamgame|
  system_game = Game.find_by_steam_app_id(steamgame[0])

  # If the game exists, add the play
  unless system_game.blank?
    # Does the game have stats recorded? If so set the achievement level
    if id.games[steamgame[0]].has_stats?
      achievement_completion = (id.game_stats(steamgame[0])).achievements_percentage * 100
    else
      achievement_completion = 0
    end
    play_time = id.total_playtime(steamgame[0])/60
```

So that User A can import from steam (id 'marknel')
His games are matched up to games in this system and his playtime/achievements are stored.

When User B attempts to import from steam (id 'krazdog')
Games (and stats) that were only owned by 'Marknel' are also imported.

This is very strange and I wondered if you could shed some light as to why this would occur.

**Comment by koraktor** [comment]
I'll have a look at it.

A few notes first:
- Calling `SteamId.clear_cache` will clear the cache for `SteamId` objects. The IDs for `"marknel"` and `"krazdog"` are different. So clearing the cache won't do anything useful here.
- Are the contents of `id.games` already wrong? This would hint at a bug inside Steam Condenser.
- There's no `Game` class in Steam Condenser, so I don't know what this code does

**Comment by Marknel** [comment]
Thanks Sebastian,

So it's very odd.

I tried calling the SteamId.clear_cache not sure if it would work - it was
simply something to try.

I take the results of the iteration and add them directly to an array and
return that ath the end of the function - that array somehow is typically
correct.

The 'Game' class is my own and is an internal representation of a Game
(this system integrates with platforms beyond steam (PS, XBox etc).

I'll try and get you an example result set so you can see it happen.

I have not been able to get it to occur through the Ruby console yet - only
through the actual site (dev or production mode)

**Comment by koraktor** [comment]
Is your code open source or can you extract the respective part? I'd like to take a look at it.

**Comment by Marknel** [comment]
I have not made the project opensource just yet. I can however extract the
relevant part - essentially it's a very small library that I made for
importing a user's "Play" stats.

A copy of the lib is here:
https://gist.github.com/dc64fdd13b68315fcd1a

I have been attempting to replicate the issue and it seems very much
random. If anything doesn't make sense please let me know.

Thanks,
Mark.

**Comment by koraktor** [comment]
I can't see anything in your Gist that could cause your issue. Maybe it's the code calling this method.

You should check that first and especially have a look at error handling, because of [this](https://twitter.com/steamcondenser/status/268483978233782272). I'd guess it's some `rescue` clause that doesn't reset a variable.

**Comment by Marknel** [comment]
Exactly my thoughts as well.

I'd noticed I was getting a lot of failures today through the API. I'll put
in some more logs and do some more error catching. I will update you once I
have some hard repeatable data.

Thanks again
Mark

**Comment by koraktor** [comment]
Any update on this issue?

**Comment by Marknel** [comment]
Apologies, I haven't found the time yet to work on the Steam integration -
I'm still having trouble finding a way to reliably replicate it - or track
it when it occurs. I'll keep you posted when I have some usable information
for you.

On Thu, Dec 27, 2012 at 10:26 PM, Sebastian Staudt <notifications@github.com

**Comment by koraktor** [comment]
I'm closing this as there hasn't been any useful information in the past years. Feel free to update this if you're still experiencing this problem.
