### ISSUE TITLE
Game_Stats call failing for game ID 201490 (which passes 'has_stats?')

### ISSUE THREAD

**Issue by Marknel** [koraktor/steam-condenser#174]
Hi Sebastian,

Just discovered that this game is erroring when I attempt to pull its stats.

> id = SteamID.new 'krazdog'
> 
> id.games[201490].has_stats?
> true
> 
> id.game_stats(201490)
> This generates an error (Nokogiri complains about invalid XML)

Just thought you might like to know.

Thanks,
Mark.

**Comment by koraktor** [comment]
This is not caused by Steam Condenser. Steam Community is _again_ causing 503s.

See http://steamcommunity.com/id/krazdog/stats/201490?xml=1 or http://steamcommunity.com/id/krazdog/stats/AirlineTycoon2.

PS: This may also be related to your issue #173.

**Comment by Marknel** [comment]
Apologies - you must hate me for contacting you this much, but one of my
users doesn't have any recent steam games, and it has raised an error while
pulling in his stats.

Line 281 of the steam_id.rb file - I believe it should be an 'unless' not
an 'if'.

Thanks,
Mark.

**Comment by koraktor** [comment]
No, I'm totally fine with any bug reports / feature requests. I'd have liked it even more if you opened another issue. But nevermind, I created one (#175). Will be fixed soon.
