### ISSUE TITLE
Change map -> Could not read from socket.

### ISSUE THREAD

**Issue by CEikermann** [koraktor/steam-condenser#176]
If I want to change the map, everytime I recieved this exception: 
https://github.com/koraktor/steam-condenser-php/blob/master/lib/Socket.php#L119

How to reproduce?
$test = new SourceServer('127.0.0.1', 27015);
$test->rconAuth('local');
$test->rconExec('changelevel de_dust');

I think, this exception is thrown because of the server is not responding, because the server is switching the level. But wow we can improve the socket, that in this case is no exception throwing?

Currently, I have fixed it with a try catch block in my application

**Comment by CEikermann** [comment]
It seems to be like the socket is after a map change broken. I get after that everytime the Exception "Could not send data" PHP Error: Broken Pipe - Do you have an idea to solve this problem?

https://github.com/koraktor/steam-condenser-php/blob/master/lib/Socket.php#L163

**Comment by koraktor** [comment]
What version are you using? The newest code from `master` includes code to better handle some edge cases during RCON, most notably this commit: koraktor/steam-condenser-php@fb5cca15edf0b534123e397357df11b15e5eef22.

**Comment by CEikermann** [comment]
Hello,

i'm using the newest code from master and i have tested two different scripts
1. Testing changelevel only:
   
   <pre>
   $test = new SourceServer('127.0.0.1', 27016);
   $test->rconAuth('local');
   $test->rconExec('changelevel de_dust');
   </pre>
   
   Exception: Could not read from socket.
2. Testing saying after changelevel:
   
   <pre>
   $test = new SourceServer('127.0.0.1', 27016);
   $test->rconAuth('local');
   try {
   $test->rconExec('changelevel de_dust');
   } catch (Exception $e) {
   }
   $test->rconExec('say blub');
   </pre>
   
   Exception: Could not send data.
   Warning: socket_send(): unable to write to socket [32]: Broken pipe in ../steam-condenser-php/lib/Socket.php on line 157

Are you able to reproduce these exceptions?

**Comment by koraktor** [comment]
Just tested this with the current code from `master`, works like a charm.

**Comment by CEikermann** [comment]
I have debugged a little bit with the code from the master. I have added a var_dump($responsePacket) at https://github.com/koraktor/steam-condenser-php/blob/master/lib/steam/servers/SourceServer.php#L136  and I did not receive any packet from the server only one RCONExecResponse

<pre>
object(RCONExecResponse)#6 (3) {
  ["requestId:private"]=>
  int(38688)
  ["contentData:protected"]=>
  object(ByteBuffer)#7 (4) {
    ["byteArray:private"]=>
    string(2) ""
    ["capacity:private"]=>
    int(2)
    ["limit:private"]=>
    int(2)
    ["position:private"]=>
    int(0)
  }
  ["headerData:protected"]=>
  int(0)
}
</pre>

And after that packet, the packet is null and I get an RCONNoAuthException exception.
I tested with PHP 5.3 and without sockets.

After that, I tested it with PHP 5.3 and with sockets. Then I will receive the RCONExecResponse also, but not futher packets:

<pre>
object(RCONExecResponse)#6 (3) {
  ["requestId:private"]=>
  int(31397)
  ["contentData:protected"]=>
  object(ByteBuffer)#7 (4) {
    ["byteArray:private"]=>
    string(2) ""
    ["capacity:private"]=>
    int(2)
    ["limit:private"]=>
    int(2)
    ["position:private"]=>
    int(0)
  }
  ["headerData:protected"]=>
  int(0)
}
</pre>

And after reading this packet, the socket did not receive any data and so PHP can not read from this socket.

---

Do you test it with a changelevel command? My server don't send any response for the changelevel. The socket receive the RCONExecResponse only. Do you receive after the RCONExecResponse packets? And what packets do you receive? Can you verify this, that only one packet (RCONExecResponse) is received by changing the map on the server?

**Comment by koraktor** [comment]
I just pushed a small change (that I missed from adding to the PHP version): koraktor/steam-condenser-php@3b6c690f6f777ce6ee7810b4782c6eed4efeb9f6

I ran this code against an up-to-date CS:S server:

``` php
var_dump(PHP_VERSION);
var_dump(extension_loaded('sockets'));

$server = new SourceServer('192.168.0.5');
$server->rconAuth('test');
$server->rconExec('changelevel de_aztec');
$server->rconExec('say blub');
```

That way it should look like this:

```
string(6) "5.3.15"
bool(true)
PHP Notice:  Received packet of type RCONExecResponse in /Users/koraktor/open-source/steam-condenser/php/lib/steam/sockets/RCONSocket.php on line 110
PHP Notice:  Received packet of type RCONAuthResponse in /Users/koraktor/open-source/steam-condenser/php/lib/steam/sockets/RCONSocket.php on line 110
PHP Notice:  Received packet of type RCONExecResponse in /Users/koraktor/open-source/steam-condenser/php/lib/steam/sockets/RCONSocket.php on line 110
PHP Notice:  Received packet of type RCONExecResponse in /Users/koraktor/open-source/steam-condenser/php/lib/steam/sockets/RCONSocket.php on line 110
PHP Notice:  Received packet of type RCONExecResponse in /Users/koraktor/open-source/steam-condenser/php/lib/steam/sockets/RCONSocket.php on line 110
PHP Notice:  Received packet of type RCONExecResponse in /Users/koraktor/open-source/steam-condenser/php/lib/steam/sockets/RCONSocket.php on line 110
PHP Notice:  Received packet of type RCONExecResponse in /Users/koraktor/open-source/steam-condenser/php/lib/steam/sockets/RCONSocket.php on line 110
PHP Notice:  Received packet of type RCONExecResponse in /Users/koraktor/open-source/steam-condenser/php/lib/steam/sockets/RCONSocket.php on line 110
```

**Comment by CEikermann** [comment]
string(5) "5.3.6"
bool(true)
Notice: Received packet of type RCONExecResponse in ../steam-condenser-php/lib/steam/sockets/RCONSocket.php on line 110
Notice: Received packet of type RCONAuthResponse in ../steam-condenser-php/lib/steam/sockets/RCONSocket.php on line 110
Notice: Received packet of type RCONExecResponse in ../steam-condenser-php/lib/steam/sockets/RCONSocket.php on line 110
Fatal error: Uncaught exception 'Exception' with message 'Could not read from socket.' in ../steam-condenser-php/lib/Socket.php:119
Stack trace:
#0 ../steam-condenser-php/lib/steam/sockets/SteamSocket.php(115): Socket->recv(4)
#1 ../steam-condenser-php/lib/steam/sockets/RCONSocket.php(92): SteamSocket->receivePacket(4)
#2 ../steam-condenser-php/lib/steam/servers/SourceServer.php(135): RCONSocket->getReply()
#3 ../steam-condenser-php/test.php(10): SourceServer->rconExec('changelevel de_...')
#4 {main}
  thrown in ../steam-condenser-php/lib/Socket.php on line 119

Still not working. Maybe the bug is in PHP, because I'm using 5.3.6 currently. I will try to upgrade my php to 5.3.15 - Maybe the bug is fixed by upgrading php ;)

**Comment by CEikermann** [comment]
With the new php version, I get the same error:
string(6) "5.3.19"
bool(true)
PHP Notice:  Received packet of type RCONExecResponse in .../steam-condenser-php/lib/steam/sockets/RCONSocket.php on line 110
PHP Stack trace:
PHP   1. {main}() .../steam-condenser-php/test.php:0
PHP   2. SourceServer->rconAuth() .../steam-condenser-php/test.php:9
PHP   3. RCONSocket->getReply() .../steam-condenser-php/lib/steam/servers/SourceServer.php:105
PHP   4. trigger_error() .../steam-condenser-php/lib/steam/sockets/RCONSocket.php:110
PHP Notice:  Received packet of type RCONAuthResponse in .../steam-condenser-php/lib/steam/sockets/RCONSocket.php on line 110
PHP Stack trace:
PHP   1. {main}() .../steam-condenser-php/test.php:0
PHP   2. SourceServer->rconAuth() .../steam-condenser-php/test.php:9
PHP   3. RCONSocket->getReply() .../steam-condenser-php/lib/steam/servers/SourceServer.php:108
PHP   4. trigger_error() .../steam-condenser-php/lib/steam/sockets/RCONSocket.php:110
PHP Notice:  Received packet of type RCONExecResponse in .../steam-condenser-php/lib/steam/sockets/RCONSocket.php on line 110
PHP Stack trace:
PHP   1. {main}() .../steam-condenser-php/test.php:0
PHP   2. SourceServer->rconExec() .../steam-condenser-php/test.php:10
PHP   3. RCONSocket->getReply() .../steam-condenser-php/lib/steam/servers/SourceServer.php:135
PHP   4. trigger_error() .../steam-condenser-php/lib/steam/sockets/RCONSocket.php:110
PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not read from socket.' in .../steam-condenser-php/lib/Socket.php:119
Stack trace:
#0 .../steam-condenser-php/lib/steam/sockets/SteamSocket.php(115): Socket->recv(4)
#1 .../steam-condenser-php/lib/steam/sockets/RCONSocket.php(92): SteamSocket->receivePacket(4)
#2 .../steam-condenser-php/lib/steam/servers/SourceServer.php(135): RCONSocket->getReply()
#3 .../steam-condenser-php/test.php(10): SourceServer->rconExec('changelevel de_...')
#4 {main}
  thrown in .../steam-condenser-php/lib/Socket.php on line 119

**Comment by CEikermann** [comment]
I removed then @ at https://github.com/koraktor/steam-condenser-php/blob/master/lib/Socket.php#L113

I will the these error: Warning: socket_read(): unable to read from socket [104]: Connection reset by peer in .../steam-condenser-php/lib/Socket.php on line 114

I have checked the socket_last_error, it is 104 and the text is Connection reset by peer. It seems to be the server is closing the rcon connection? Maybe wireshark can help me.

**Comment by CEikermann** [comment]
I have created a TCP dump, maybe we can compare it with yours? Maybe you can add me on skype: christian.eikermann ?

**Comment by koraktor** [comment]
There has been a lot of effort to solve these connection resets lately, see #169.

I just read through that one and it seem like my patches for #169 didn't fully fix the connection reset `changelevel` problem discribed by @RJMiller. The most probable cause is that you set your `rcon_password` inside `server.cfg` which will be evaluated on `changelevel` and therefore reset the RCON connection.
The simple workaround for this case is to move the `rcon_password` setting into `autoexec.cfg` which is only evaluated once during server start.

I just test this and could reproduce and fix the problem as described above.

**Comment by koraktor** [comment]
This problem should be fixed by the patches above. Please try with the newest code from `master`.

**Comment by CEikermann** [comment]
I have test the newest code from master, and now everything works fine. Thank you very much :) :+1:
