### ISSUE TITLE
PHP - Errors triggered unnecessarily

### ISSUE THREAD

**Issue by ArgHereBeDragons** [koraktor/steam-condenser#18]
Im not sure if these are debug messages or intentional, but the following lines of code (58b508a462027a84634489ff2e980a3a7af0b68b commit) throw errors which break my implementation, in my case, phpBB.

GoldSrcSocket.php:60 - trigger_error("Received packet $packetNumber of $packetCount for request #$requestId");

GoldSrcSocket.php:84 - trigger_error("Received packet of type \"" . get_class($packet) . "\"");

SourceSocket.php:51 - trigger_error("Received packet $packetNumber of $packetCount for request #$requestId");

SourceSocket.php:79-84

SteamSocket.php:85 - trigger_error("Sending packet of type \"" . get_class($dataPacket) . "\"...");

I think thats all of them.

**Comment by ArgHereBeDragons** [comment]
Missed one:

GameServer.php:175 - trigger_error("Expected {$expectedResponse}, got " . get_class($responsePacket) . ".");

**Comment by koraktor** [comment]
`trigger_error()` used without a second argument results in a E_USER_NOTICE. You may ignore such errors with either using `error_reporting()` ([manual](http://www.php.net/manual/en/function.error-reporting.php)) or an [error handler](http://www.php.net/manual/en/function.set-error-handler.php).

I think there should be a way to completely disable debug output, but in the meantime this should be a good way to workaround this "problem".

**Comment by ArgHereBeDragons** [comment]
Yeah, i was disabling and re-enabling error reporting whilst wrapping steam-condenser calls, i ended up just commenting them out in the code for now.

**Comment by koraktor** [comment]
Another note on this: The preferred silence logging in PHP is do prepend the `@` operator to the line causing the errors/warning/notices. For example:

``` php
<?php
$master = SourceServer::getMaster();
$servers = @$master->getServers();
?>
```

For Ruby use:

``` ruby
$DEBUG = false
```

For Java use:

``` java
Logger.getLogger("com.github.koraktor.steamcondenser").setLogLevel(Level.WARNING);
```

I think this should be sufficient for now, but improved logging will be added in the future.

**Comment by katanacrimson** [comment]
As a note, phpBB considers all `E_USER_*` trigger_error calls to be terminal, and it takes complete control of the error handler.  You can't take over the error handler without causing significant problems to the software itself; they use `E_USER_NOTICE` for status messages (such as "Your message was posted", "Your account has been registered", etc.) for some silly reason.

The only solution would indeed be to silence warnings/notices with @.

Hope this comes in useful for anyone looking at this in the future.

**Comment by koraktor** [comment]
@damianb :+1: for that hint.

PHP's error handling is really weird, especially when it's misused for something like that. ;)

**Comment by katanacrimson** [comment]
Aye, it's why I've moved to the exception model myself for just about all errors.

I think the devs were going to stop (ab)using `trigger_error()` for the confirmation messages and such in 3.2, but then they scrapped that codebase and since then...well, it's hard to say what all is being done with what is going to be 3.1

All I know anymore is that there's been just about nil major feature additions since gold, which was...what, five years ago?
They're pretty resistant to change.
