### ISSUE TITLE
Ruby StringIO extension

### ISSUE THREAD

**Issue by Holek** [koraktor/steam-condenser#180]
Hey there,

I've noticed a small thing I would like point out in your Ruby [StringIO](https://github.com/koraktor/steam-condenser-ruby/blob/namespace/lib/core_ext/stringio.rb) extension.

[`def byte`](https://github.com/koraktor/steam-condenser-ruby/blob/namespace/lib/core_ext/stringio.rb#L27) is not needed, as Ruby [already supports that](http://apidock.com/ruby/IO/getbyte).

Is there a reason why you re-implemented it in your code?

**Comment by koraktor** [comment]
It's because Ruby 1.8.6 didn't have `getbyte`/`getc`. I guess it's fine to remove this for version 2.0.0.

**Comment by Holek** [comment]
Rbuy 1.8.6 [kicked the calendar](http://blog.engineyard.com/2011/engine-yards-plans-for-ruby-1-8-6/) over a year ago. It's safe to move on by now.

**Comment by koraktor** [comment]
That's why it will be removed from 2.0.0, which will be the next non-patch release. Expect this to land in `master` soon.

**Comment by Holek** [comment]
Awesome :+1:
