### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by koraktor** [koraktor/steam-condenser#182]
Currently, the libraries include only primitive logging that could use a major overhaul.

The way logging is done currently:
- Ruby: Simple `puts` when `$DEBUG` is active
- Java: Uses `java.util.logging.Logger` which is quite OK
- PHP: `trigger_error()` isn't really configurable and also irritates most of the users because PHP usually logs right into the output. :confused:

Logging is only done in a few places (sockets, servers, Web API) and could use more detail.

There should probably a simple, configurable and library-wide logger class that wraps around some standard logging facility of the particular platform.
- Ruby: logger or log4r
- Java: slf4j or log4j
- PHP: Monolog, Zend_Log, Analog or KLogger

**Comment by Ph3nol** [comment]
+1 about Monolog utilization for PHP ! :)

**Comment by koraktor** [comment]
Small update on this one.

Ruby will use a lightweight wrapping around `Logger`. No external dependencies are added and it should integrate well with existing applications.

Java will use SLF4J. It's also lightweight and allows to fit into almost any existing application.

I still have to dive into PHP, but Monolog seems like a good fit right now.

**Comment by koraktor** [comment]
This was implemented in koraktor/steam-condenser-php@fe04723069275a317fe97f3a23a127dc568bb0ed for PHP. So I guess this can be closed now.
