### ISSUE TITLE
NullPointerException with some TF2 Items

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#184]
I am querying this guys backpack :http://backpack.tf/profiles/76561197971691194
but when I try to print out the name of every item, I get a lot of NullPointerExceptions when I get the name of the item. This happens on the team captains and the unusuals.

**Comment by koraktor** [comment]
Can you provide a backtrace of such an NPE?

**Comment by sainaetr** [comment]
probably same cause, check this : https://github.com/koraktor/steam-condenser/issues/187

**Comment by koraktor** [comment]
@Alem101 What code do you use to iterate over the inventory's items? The following worked for me without problems:

``` java
GameInventory inv = GameInventory.create(440, 76561197971691194L);
for (GameItem i : inv.getItems().values()) {
    System.out.println(i.getName());
}
```

**Comment by koraktor** [comment]
Any news on this issue? Otherwise I'm going to close it.

**Comment by sainaetr** [comment]
I am not sure but issue #187 should have fixed it.

**Comment by koraktor** [comment]
I'm not sure. This may also be related to either some other edge case we don't know yet or a bug in the calling code.

**Comment by koraktor** [comment]
Closing this as long as there's no additional information.
