### ISSUE TITLE
Checking an Inventory for an Item

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#185]
I want to check if an inventory has a certain item, such as a Salvaged crate 40, but I can't figure out how. When I try to create a TF2Item, it asks for a inventory, so I assume I have to put the user I am checking there, but it also asks for a JSONData, and I'm not sure what to do for that.

**Comment by koraktor** [comment]
You have to get the inventory and check if the item is contained in it.

Example:

``` java
GameInventory inv = GameInventory.create(440, "koraktor");
for (GameItem item : inv.getItems().getValues()) {
    // Do your check here, e.g. check the defindex of the item
    item.getDefIndex() == 1234
}
```

PS: You cannot (or at least should not) create instances of `GameItem` (or its subclasses) manually.
