### ISSUE TITLE
Way to find if a user is F2P?

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#186]
Is there a way to find if a user is premium or not in TF2?

**Comment by koraktor** [comment]
I don't think there's a direct method to check this.

But to my knowledge F2P players only have 100 item slots in their backpack, so you could just check the size of the inventory using `GameInventory#size()`.

**Comment by koraktor** [comment]
I presume that Valve won't add any API to retrieve this information. So I'm going to close this.
