### ISSUE TITLE
Recent Traded Items is not Shown.

### ISSUE THREAD

**Issue by sainaetr** [koraktor/steam-condenser#187]
lets say R = "recently dropped/traded item" and Rs is plural form.

while fetching items, since Rs do not have backpack position, all Rs use same index, so last fetched R is only stored.
As a side effect, number of items are higher than the content of the list and for missing points in $list, we get a lot of null pointer. corresponding method is below:

```
public function fetch() {
    $params = array('SteamID' => $this->steamId64);
    $result = WebApi::getJSONData("IEconItems_{$this->getAppId()}", 'GetPlayerItems', 1, $params);

    $this->items = array();
    foreach ($result->items as $itemData) {
        if ($itemData != null) {
            $inventoryClass = new ReflectionClass(get_class($this));
            $itemClass = $inventoryClass->getConstant('ITEM_CLASS');
            $item = new $itemClass($this, $itemData);
            $this->items[$item->getBackpackPosition() - 1] = $item;
        }
    }

    $this->fetchDate = time();
}
```

this is how I quick fixed it:

```
public function fetch() {
    $params = array('SteamID' => $this->steamId64);
    $result = WebApi::getJSONData("IEconItems_{$this->getAppId()}", 'GetPlayerItems', 1, $params);

    $this->items = array();
    $i = 0;
    foreach ($result->items as $itemData) {
        if ($itemData != null) {
            $inventoryClass = new ReflectionClass(get_class($this));
            $itemClass = $inventoryClass->getConstant('ITEM_CLASS');
            $item = new $itemClass($this, $itemData);
            $this->items[$i] = $item;
            $i++;
        }
    }

    $this->fetchDate = time();
}
```

this happens on tf2, might also occur on dota2 but do not have any idea on other games.

**Comment by koraktor** [comment]
What's the index returned by `getBackpackPosition()` for such an item? That seems like a strange inconsistency in the Web API.

**Comment by sainaetr** [comment]
it returned 3 for 22 of them, and 0 for 2 of them out of total 530 items in which 22+3 items are Rs.

**Comment by koraktor** [comment]
@bluebrain- Do you have one or more sample inventories that show this behavior at the moment? I wasn't able to reproduce this, yet.

**Comment by sainaetr** [comment]
try mine   steamID:  bluebrain_  
or  http://www.tf2outpost.com/backpack/115956

**Comment by koraktor** [comment]
Thanks, found the cause for this. Should've read the docs a bit better. :dizzy_face:

**Comment by sainaetr** [comment]
you are welcome, PS: probably same reason causes https://github.com/koraktor/steam-condenser/issues/184

**Comment by koraktor** [comment]
The commits above fix this problem by adding a separate part of the inventory, called `preliminaryItems`. I decided not to mix this with the rest of the inventory because I don't want to break the item positions inside the inventory's array. Having a separate collection for those items also seems useful, because it's more obvious to the user that there are items in the inventory that are not yet _active_.
