### ISSUE TITLE
Server initialization fails when used just after boot

### ISSUE THREAD

**Issue by losttime** [koraktor/steam-condenser#188]
I have a server that notifies me as soon as it's powered up and has started the source game server. I am then using steam-condenser (PHP version) to query the game server status, like this:

``` php
$server = new SourceServer('ip-address-returned-by-server');
$server->initialize();
```

The initialize call does not complete and hangs up my web server unless I wait a few minutes. I know I'm probably calling it too soon, but it would be great if the initialization could fail gracefully.

I've traced it to the receivePacket method of the SteamSocket class (which is called a few steps after the updatePing method of the GameServer class). The call to `socket->recv()` throws an Exception, but the code in the catch block also fails.

I have modified my local copy of steam-condenser so the catch block in receivePacket() simply re-throws the Exception rather than trying to find the length of the remaining buffer. I have also added the try/catch blocks to the updatePing() method so the rethrown Exception can be caught.

I will submit a pull request when I've confirmed that it's still working as it should, but I'm concerned because of the code a removed from the catch block in the receivePacket method. I'm sure it was there for a reason, so I'm sure my code breaks something else.

**Comment by koraktor** [comment]
Thanks for reporting this problem.

First of all, it seems really strange that the call to `SteamSocket::recv()` blocks when the socket is checked to be readable just a [few lines above](https://github.com/koraktor/steam-condenser-php/blob/master/lib/steam/sockets/SteamSocket.php#L105-L107).

For clarification: The second call to `recv()` inside the `catch` clause was added [recently](https://github.com/koraktor/steam-condenser-php/commit/0578267cf0c341eac38f00bd3db25c3e985d4c9b) to detect reset connection during RCON. This is pretty hackish, but seems to be the only reliable way to do this in PHP.

**Comment by losttime** [comment]
After some more testing, it looks like the first call to `Socket::recv()` results in a Refused Connection (error code 111 returned from socket_read()). Then, when `Socket::recv()` is tried again in the catch block, socket_read() hangs, presumably waiting for a response.

I'm not very familiar with the behavior of sockets, but it seems like the connection is being terminated or otherwise invalidated at some point, so maybe the catch block needs to reconfirm the validity of the connection before trying to red the data again.

**Comment by koraktor** [comment]
That makes sense. I already have an idea how to fix this. Stay tuned.

**Comment by losttime** [comment]
I think I have a viable fix in place on my system. I've already forked the project, so I'll start updating my version of the code. You can take a look at it when I'm done and see how it compares to your solution. I'll happily convert over to yours as long as it works :)

**Comment by koraktor** [comment]
I've implemented [a fix](https://github.com/koraktor/steam-condenser-php/compare/f924e30c20292225785fdc004cd3ed899490d29d...8122564a49534407dbb70f45315a5cc338a4ed8d) that's quite similar to your pull request (koraktor/steam-condenser-php#10), but also builds on better socket error handling in general. That's something I wanted to do for a long time.

**Comment by losttime** [comment]
Looks great now. Thanks :)

**Comment by koraktor** [comment]
Fine.
