### ISSUE TITLE
PHP - Public data methods missing from SteamPlayer.php for extended player info with status command

### ISSUE THREAD

**Issue by ArgHereBeDragons** [koraktor/steam-condenser#19]
The following data items are set when using the status command to get extended player info but no matching methods exist to return the date from the class.

extended
loss
ping
state

The __toString() function does not reflect these data items either.

**Comment by koraktor** [comment]
Those are definitely needed. Thanks for your report.

**Comment by ArgHereBeDragons** [comment]
This is now covered in issue - http://github.com/koraktor/steam-condenser/issues#issue/21

**Comment by koraktor** [comment]
This is fixed in 732f3b647ca7ea9deb43f3b2cdbb791b33d20849.
