### ISSUE TITLE
"Connection reset by peer" after changelevel

### ISSUE THREAD

**Issue by CEikermann** [koraktor/steam-condenser#190]
Hello,

I found a wired bug, it is 100% reproducible with the current code from master.

Everytime I send the "changelevel" command to a CS:S server, the server response immedetly with "Connection reset by peer (Code: 104)" which is catched by the RCONSocket class and is throwing an RCONBanException.

But our IP is not banned on the server and the command was executed on the server and the server changed the map.

Do you know how to solve this problem? I think, we have already a similar bug ticket.

CSS Server Version: v1.0.0.75 (Linux, Dedicated, Protocol 17)
Installed Plugins: Nothing
Installed Anticheat Tools: VAC, zBlock v4.68

Best regards,
Christian

**Comment by CEikermann** [comment]
Additional Information:
It is not reproducible with all css server, I have one server with this "strange behavior" and I have an another one without this behavior, but i think, there is no differences between these servers.

**Comment by koraktor** [comment]
Any difference in the configuration of the servers? Especially where is `rcon_password` set?

**Comment by koraktor** [comment]
Any chance you can try the code from [`improve-ban-detection`](https://github.com/koraktor/steam-condenser-php/tree/improve-ban-detection)?

The [patch](https://github.com/koraktor/steam-condenser-php/compare/improve-ban-detection) introduces a, what I think, cleaner and more straight-forward method of handling RCON bans.

**Comment by CEikermann** [comment]
Hello,

"Any difference in the configuration of the servers? Especially where is rcon_password set?"
What do you mean with "where the rcon is set"? - Do you mean at the begin or end of the file? Or defined in another Config file, which is executed by the main server.cfg ?

I have written some functional tests with a real gameserver behind. For CS, CSS and CSGO. And test it again the master and the improve-ban-detection branch.

Changelevel (valid server ip/port + rcon):

<table>
  <tr>
    <th>Index</th><th>Game</th><th>Master Branch</th><th>improve-ban-detection Branch</th>
  </tr>
  <tr>
    <td>1</td><td>CS</td><td>Ok (no exception)</td><td>Ok (no exception)</td>
</tr>
  <tr>
    <td>2</td><td>CSS</td><td><b>RCONNoAuthException</b></td><td><b>RCONBanException</b></td>
</tr>
  <tr>
    <td>3</td><td>CSGO</td><td>Ok (no exception)</td><td>Ok (no exception)</td>
  </tr>
</table>

IP is banned on server, but server ip/port and rcon still valid:

<table>
  <tr>
    <th>Index</th><th>Game</th><th>Master Branch</th><th>improve-ban-detection Branch</th>
  </tr>
  <tr>
    <td>1</td><td>CS</td><td><b>TimeoutException</b></td><td><b>TimeoutException</b></td>
  </tr>
  <tr>
    <td>2</td><td>CSS</td><td>RCONBanException</td><td>RCONBanException</td>
  </tr>
  <tr>
    <td>3</td><td>CSGO</td><td><b>No exception</b></td><td><b>No exception</b></td>
  </tr>
</table>

At the changelevel test, index 2 with CSS gameserver, the library is throwing a RCONBanException at the improve-ban-detection Branch.  But the IP is not banned on the server.
At the ip ban test, index 1 with CS gameserver, the library is throwing a TimeoutException, but I think it is not possible to throw a ban exception because of the CS server don't response anything.
Another ip test, index 3 with CS:GO gameserver, the library is nothing thrown, maybe we can fix this.

I hope, my test results helps a little bit.

**Comment by koraktor** [comment]
According to earlier tests, the state of RCON connections during `changelevel` depends on the place where `rcon_password` is set, e.g. in `autoexec.cfg` or `server.cfg`.

However, thanks for the detailed report, this will help a lot. The main problem I have now is that I usually test against a CS:S server which worked flawlessly with the `improve-ban-detection` branch. I'll also install CS 1.6 and CS:GO to cross-check this. Please note that CS 1.6 has a different RCON protocol (UDP) and wasn't affected by the recent changes.

Could you provide a small code snippet that you used to test?

**Comment by CEikermann** [comment]
Hey,

yeah, I have added the tests to my repo. -> https://github.com/CEikermann/steam-condenser-php/commit/33f584cb32ddfb24d55efeaf9a97a1f5c317b1b2

Please note that CS 1.6 has a different RCON protocol (UDP) and wasn't affected by the recent changes.
Yes, I think, that is the reason for the TimeoutException when the IP is banned. But it is okay for CS1.6 ;)

About the server.cfg and autoexec.cfg, I will ask the server owner of the corrupted server, hopely I get a response.

**Comment by CEikermann** [comment]
I think, you have to change the following line (change it to your real local ip ;)):
https://github.com/CEikermann/steam-condenser-php/blob/functional-tests/tests/functional/ServerTest.php#L207

**Comment by koraktor** [comment]
:flushed: 

That was easy, the exception thrown in `SourceServer::rconExec()` was simply wrong. I updated `improve-ban-detection`. That should fix the behavior of CS:S.

Next one is CS:GO. :wrench:

**Comment by CEikermann** [comment]
:+1: I will test it with my functional tests tomorrow ;)

**Comment by koraktor** [comment]
As far as I can see CS:GO doesn't ban clients from RCON when added via `addip`. Only automatic banning (e.g. when failing to authenticate multiple times) works and shows the same connection behavior as CS:S.

**Comment by koraktor** [comment]
@CEikermann Any news on this? If it works, I'll merge it into `master` and release a new version soon.

**Comment by CEikermann** [comment]
Hello,
yes, sure I can test it again, have you pushed your code to github?

**Comment by koraktor** [comment]
Yes.

**Comment by CEikermann** [comment]
I can't seen any new commit on improve-ban-detection branch. Your last commit was https://github.com/koraktor/steam-condenser-php/commit/67e874b61b72935db4ac0dc31bb78a15519cc058 - but this commit was already tested and results are written down here: https://github.com/koraktor/steam-condenser/issues/190#issuecomment-12652642

**Comment by koraktor** [comment]
The commit was amended.

**Comment by CEikermann** [comment]
The ban detection works perfectly now.

But I get still the RconNoAuthException when I changed the map on a CSS server (the rcon_password is defined in the server.cfg at the top of the file).

**Comment by CEikermann** [comment]
The following tests are still failing (But only with a CSS gameserver):
https://github.com/CEikermann/steam-condenser-php/blob/functional-tests/tests/functional/ServerTest.php#L170
https://github.com/CEikermann/steam-condenser-php/blob/functional-tests/tests/functional/ServerTest.php#L184

**Comment by koraktor** [comment]
This is normal as Source servers do reset the TCP connection for RCON when setting `rcon_password`. It's a good practice to wrap your code (e.g. when using `changelevel` or `rcon_password`):

``` php
if ($server->rconAuth($password)) {
    try {
        $server->rconExec($command);
    } catch (RCONNoAuthException $e) {
        // Although we authenticated successfully earlier, it has been revoked
        // Either inform the user that he has to try again ...
        // ... or if you still have the password do it automatically
    }    
}
```

**Comment by CEikermann** [comment]
Okay then everything works fine ;) - I think, you can merge it into the master ;)
