### ISSUE TITLE
reassemblePacket failing due to default charset bug

### ISSUE THREAD

**Issue by mon** [koraktor/steam-condenser#192]
I've never used github, so I've got no idea how to submit a patch. Sorry.

At the end of 
public static SteamPacket reassemblePacket(ArrayList<byte[]> splitPackets, boolean isCompressed, int uncompressedSize, int packetChecksum) throws SteamCondenserException 

in SteamPacketFactory.java

is the line:
packetData = new String(packetData).substring(4).getBytes();

On my system, this conversion somehow got borked by charset silliness (win7 x64) and broke the server rules feature, giving some exception about arrays not allowed to be of size -1674 (because the start of the data was broken by the conversion and it couldn't read the Short properly).

A platform/charset agnostic fix for this is to replace the offending line with:
        tmpData = packetData;
        packetData = new byte[tmpData.length - 4];
        System.arraycopy(tmpData, 4, packetData, 0, tmpData.length - 4);

It then works fine.

**Comment by koraktor** [comment]
Sounds reasonable, I never liked that `String` construct, but had no reason to change it, yet.

PS: If you like to contribute, have a look at [GitHub's help pages](https://help.github.com/articles/fork-a-repo).
