### ISSUE TITLE
Unable to retrieve message from WebApiException

### ISSUE THREAD

**Issue by Yeggstry** [koraktor/steam-condenser#193]
When trying to retrieve the exception message from the following throw:

throw new WebApiException("Invalid appId or steamId");

the message appears to be null. Having dug around it appears that the getMessage() method is overwritten, and this is used for the following exception call:

WebApiException(Cause cause, Integer statusCode, String statusMessage)

the first call store the message in the detailedMessage attribute of the Throwable class. However, this can't be reached.

**Comment by Yeggstry** [comment]
For reference, this test fails:

```
@Test
public void testWebApiException() {
    try {
        throw new WebApiException("Invalid appId or steamId");
    }catch(Exception e) {
        assertEquals("Invalid appId or steamId", e.getMessage());
    }

}
```

**Comment by koraktor** [comment]
Thanks.

**Comment by Yeggstry** [comment]
Thanks for the fix :) This will give me the challenge of trying to merge it into my fork (never used Git before :)).
