### ISSUE TITLE
1.3.3 - CS:GO - JAVA - OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by danielsawan** [koraktor/steam-condenser#198]
When i try to execude command :  changelevel mapName
i go this error : 

Execution exception [[OutOfMemoryError: Java heap space]]
java.util.Arrays.copyOf(Arrays.java:2760)
java.util.Arrays.copyOf(Arrays.java:2734)
java.util.ArrayList.ensureCapacity(ArrayList.java:167)
java.util.ArrayList.add(ArrayList.java:351)
com.github.koraktor.steamcondenser.steam.sockets.RCONSocket.getReply(RCONSocket.java:123)
com.github.koraktor.steamcondenser.steam.servers.SourceServer.rconExec(SourceServer.java:183)

The main problem here it is that not all rconExec are failing only sometimes...
Seems like it depends of the state of the csgo server. 
And this is not an xmx problem.
Any idea ?

**Comment by koraktor** [comment]
Is there a (reliable) way to reproduce this behavior?

**Comment by danielsawan** [comment]
not yet :( i am trying to reproduce this issue right now. But i think that an out of memory exception should never happen even if the server is in an "unstable mode". There is maybe a loop trying to do something whithout success and trying it again and again ? (i didn't look the code right now).

**Comment by danielsawan** [comment]
i just find this issue and i understand why it only happen in production.
If the server is empty the "changelevel mapName" command work.
when i connect to the server and i send the "changelevel mapName" command i go in outofmemory
It happen all the time only if there is at least 1 player on the server.

**Comment by danielsawan** [comment]
And this is really only this command.
For example when i connect to the server and i send command 
mp_restartgame 5
evrything is ok.
then i type : changelevel de_nuke
And boom outofmemory.

There is something strange with changelevel command...

**Comment by danielsawan** [comment]
do you manage to reproduce the bug in your dev env ?

**Comment by koraktor** [comment]
Not yet. I'll first have to get my CS:GO test server up and running.

**Comment by koraktor** [comment]
No sorry. `changelevel` alone doesn't seem to trigger that behavior (tested on an empty server and with bots and real players).

But I had a look at the problematic lines in `RCONSocket` and finally got rid off the ugly byte handling.

You may want to apply this patch and see if it improves the situation.

``` patch
 .../steamcondenser/steam/sockets/RCONSocket.java         | 16 ++--------------
 1 file changed, 2 insertions(+), 14 deletions(-)

diff --git a/src/main/java/com/github/koraktor/steamcondenser/steam/sockets/RCONSocket.java b/src/main/java/com/github/koraktor/steamcondenser/steam/sockets/RCONSocket.java
index 7c089d0..311a69f 100644
--- a/src/main/java/com/github/koraktor/steamcondenser/steam/sockets/RCONSocket.java
+++ b/src/main/java/com/github/koraktor/steamcondenser/steam/sockets/RCONSocket.java
@@ -11,8 +11,6 @@ import java.io.IOException;
 import java.net.InetAddress;
 import java.nio.ByteBuffer;
 import java.nio.channels.SocketChannel;
-import java.util.ArrayList;
-import java.util.List;
 import java.util.concurrent.TimeoutException;
 import java.util.logging.Logger;

@@ -112,24 +110,14 @@ public class RCONSocket extends SteamSocket {
         int packetSize = Integer.reverseBytes(this.buffer.getInt());
         int remainingBytes = packetSize;

-        byte[] packetData;
-        List<Byte> packetDataList = new ArrayList<Byte>();
+        byte[] packetData = new byte[packetSize];
         int receivedBytes;
         do {
             receivedBytes = this.receivePacket(remainingBytes);
-
-            packetData = this.buffer.array();
-            for(int i = 0; i < this.buffer.limit(); i ++){
-                packetDataList.add(packetData[i]);
-            }
+            System.arraycopy(this.buffer.array(), 0, packetData, packetSize - remainingBytes, receivedBytes);
             remainingBytes -= receivedBytes;
         } while(remainingBytes > 0);

-        packetData = new byte[packetDataList.size()];
-        for(int i = 0; i < packetData.length; i ++) {
-            packetData[i] = packetDataList.get(i);
-        }
-
         RCONPacket packet = RCONPacketFactory.getPacketFromData(packetData);

         LOG.info("Received packet of type \"" + packet.getClass() + "\".");
```

**Comment by danielsawan** [comment]
when i apply this modification i got maven test error : 
Tests in error: 
  testReceiveReply(com.github.koraktor.steamcondenser.steam.sockets.RCONSocketTest)

**Comment by koraktor** [comment]
I know, I have a modification for that test, too. You can ignore it for the time being.

**Comment by danielsawan** [comment]
this patch fix my bug.
Nice shot :+1:
