### ISSUE TITLE
PHP - Status based player information - regex failed match on splitting status data

### ISSUE THREAD

**Issue by ArgHereBeDragons** [koraktor/steam-condenser#20]
SouceServer.php:41 - splitPlayerStatus Function

The regex here:

preg_match('%#( \d|\d\d) +"(._)" +(._)%', $playerStatus, $playerData);

fails to match due to there being either 1 or 2 spaces after the # char for the 'userid' data field. Changing the regex to:

preg_match('%# ( \d|\d\d) +"(._)" +(._)%', $playerStatus, $playerData);

Appears to fix this for me (1 extra space before "(/d|/d/d)" ). I cannot find any information on the behaivour of the userid field and its maxlength or how the space padding works here either, so this may not be an infallible solution.

**Comment by ArgHereBeDragons** [comment]
ok, i just noticed the userid field grow beyond 99 so the following regex would be more appropriate i think:

preg_match('%# ( \d|\d_) +"(._)" +(.*)%', $playerStatus, $playerData);

**Comment by koraktor** [comment]
I think the best regex would be something like `%# *(\d+) +"(.*)" +(.*)%`
This should be good for all cases. You see, I didn't have a live server to test this.

Maybe I'll do some benchmarking to see which regex is the fastest.

**Comment by ArgHereBeDragons** [comment]
I fail at regular expressions quite a lot. The one you posted here works good enough for me tho.

I just found yet another problem with this though, it appears as though sometimes there may be more than one space between steam_id and connected fields in the status return data. Possibly then, in even more places. Ive overcome this for now by adding:

$playerData = str_replace( '  ', ' ', $playerData );

after the 

array_shift($playerData);

in SourceServer->splitPlayerStatus()

Sorry for finding all these issues, but ive commited myself to getting steam-condenser working for me!

**Comment by koraktor** [comment]
Thanks again. Seems like the output format is quite dynamic - which is really bad for parsing.

PS: I've commited myself to get Steam Condenser working for as many people as possible. ;)

**Comment by koraktor** [comment]
This is now fixed in d470108df1f8d6186863f3e6b3ad4e266346b2eb and d88d2e8bf5c65cac4f0781313f06c215eeb0f2ae respectively.
