### ISSUE TITLE
Incorrect game play times returned

### ISSUE THREAD

**Issue by duizendnegen** [koraktor/steam-condenser#201]
60 minutes instead of 87811 minutes are returned when querying my TF2 playing time.

Compare (correct 87811):
http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=INSERT_KEY_HERE&steamid=76561198007646341&format=json
or (also correct 1463.5)
http://steamcommunity.com/id/duizendnegen/games?xml=1
vs (incorrect 60)
`$id = SteamId::create('76561198007646341');
$id->getTotalPlaytime("tf2");`

**Comment by Yeggstry** [comment]
For your information the current code doesn't use the new service at this time, which are underlying issues highlighted in #195 and  #199.

**Comment by duizendnegen** [comment]
Understood; 1463.5 is a great value (87811 minutes converted to hours, so)
However, the code as provided still returns 60, so is still incorrect unfortunately.

**Comment by Yeggstry** [comment]
The problem with using hours with a floating point is that its not entirely accurate; 1463.5 \* 60 is 87810. There isn't anything we can really do about this, but at least the Web API provides this value in minutes :)

**Comment by koraktor** [comment]
The current code should work as expected.

@duizendnegen What version are you using? There was a bug (#171) in versions prior to 1.3.0 which could cause this.

**Comment by duizendnegen** [comment]
Ah, that solved my issue.
I was using 1.2.2 (downloaded it because I followed the Download link from the Steam Wiki, leading to https://github.com/koraktor/steam-condenser/downloads - where 1.2.2 is the lastest package).

**Comment by koraktor** [comment]
Great. I also updated the link on VDC.
