### ISSUE TITLE
SteamGame.getIconUrl() returning Null?

### ISSUE THREAD

**Issue by gcoelho** [koraktor/steam-condenser#202]
Hi,

I´m getting a Null from SteamGame.getIconUrl() method. Using Steam Condenser 1.3.2.

Any advice?

Tks!

**Comment by koraktor** [comment]
Can you provide any details? How did you get your `SteamGame` instance and what game?

**Comment by gcoelho** [comment]
Sure! I will post some code fragment over the weekend for you. I get valid data for other methods (getAppId(), getLogoUrl(), for example) for the same SteamGame object that returns "null" for getIconUrl(). I´m getting "null" for all games i have.

Tks!

**Comment by gcoelho** [comment]
Here is some code to get this bug.

# 

```
private void runTestGetIconUrl() {
    try {
        SteamId steamId = SteamId.create("gcoelho");
        steamId.fetchData();
        HashMap<Integer, SteamGame> games = steamId.getGames();
        for (Map.Entry<Integer, SteamGame> entry : games.entrySet()) {
            SteamGame game = entry.getValue();
            System.out.println("AppDd: " + game.getAppId());
            System.out.println("Name: " + game.getName());
            System.out.println("ThumbUrl: " + game.getLogoThumbnailUrl());
            System.out.println("LogoUrl: " + game.getLogoUrl());
            System.out.println("IconUrl: " + game.getIconUrl());
            System.out.println("\n");
        }

    } catch (SteamCondenserException e) {
        System.out.println(e);
    }
}
```

# 

Let me know if you want some help do debug steam-condenser.

Tks!

**Comment by Yeggstry** [comment]
The [Games feed page](http://steamcommunity.com/id/gcoelho/games?xml=1) doesn't contain an icon URL, only a logo URL. From looking at the code I believe the getIconUrl() is only to be used when parsing the [Profile feed page](http://steamcommunity.com/id/gcoelho/?xml=1), however it looks like the most played games aren't being parsed to this detail.

**Comment by koraktor** [comment]
That's it, @Yeggstry hit the nail on the head with this one. Steam's APIs are somewhat inconsistent. :sleeping:
I decided to provide the available information without forcibly stripping out parts that aren't available everywhere. I must admit, that the documentation of those parts should explicitly mention that.

**Comment by gcoelho** [comment]
Ok, Tks!
