### ISSUE TITLE
Port steam-condenser to Python

### ISSUE THREAD

**Issue by pmrowla** [koraktor/steam-condenser#204]
I've started a Python port here: https://github.com/pmrowla/steam-condenser-python

Also, I went ahead and registered the pypi package at https://pypi.python.org/pypi/steam-condenser/0. I can transfer the pypi package ownership/maintainer status to whoever it should go to though.

**Comment by pmrowla** [comment]
The WebApi tests are actually passing, but the current travis build fails because the community.steam module is currently trying to import classes that don't exist yet.

**Comment by koraktor** [comment]
Great, maybe you (or anyone else) is willing to complete and maintain this?

I'm not a Python guy. :relaxed:

**Comment by pmrowla** [comment]
Yeah I'm still working on it, and can maintain it once it's done.

**Comment by koraktor** [comment]
Looks like this was abandoned a long time ago.
