### ISSUE TITLE
Is this api supported?

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#207]
http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=193.219.1.235&format=json

This will check if your server is in the master list and give an explanation on why it is not for example. It is an official API.

**Comment by koraktor** [comment]
No, this is currently not used in Steam Condenser, but can be easily accessed via the `WebApi` class. It may be added in the future, but currently I don't have a valid use case that would integrate into the other components.

**Comment by Yeggstry** [comment]
This is part of the code I wrote to resolve [this issue](https://github.com/koraktor/steam-condenser/issues/197), so this may help in the future.

**Comment by koraktor** [comment]
Closing this as a duplicate of #197.
