### ISSUE TITLE
Steam condenser rcon tool

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#208]
Hey, I have written a tool to access the rcon through the console using steamcondenser, thanks to steamcondenser I didn't have to write much.

``` ruby
#!/usr/bin/env ruby

require 'steam-condenser'
require 'readline'

s = GoldSrcServer.new(ARGV[0], ARGV[1].to_i)
s.rcon_auth(ARGV[2])

while cmd = Readline.readline("> ", true)
  break if cmd == "exit"
  puts s.rcon_exec(cmd)
end
```

What I would like to see is a gem which has several tools based on steamcondenser, like the one above. I would like to name it steam-condenser-utils or steam-condenser-bin so it would be easy to install them on every platform and use them immediately.

However, I don't want to take away your namespace, since the steam-condenser prefix belongs to you @koraktor 

I want to hear what you think about it.

**Comment by koraktor** [comment]
What about a completely different name? Basing a tool on a specific library is nothing uncommon, but that doesn't necessarily mean that it will stay like that forever. You may add support for other libraries or change to another one later. Additionally, this somewhat implies a close relationship between Steam Condenser and your tools which isn't a problem per se, but usually causes confusion amongst users.

**Comment by txdv** [comment]
You are right, i'll just name them steam-utils
