### ISSUE TITLE
PHP - SteamPlayer class changes

### ISSUE THREAD

**Issue by ArgHereBeDragons** [koraktor/steam-condenser#21]
(This relates to the issue here - http://github.com/koraktor/steam-condenser/issues#issue/19)

I have identified a number of issues in SteamPlayer.php and rectified them in the following dump:

http://pastebin.com/f1f4155a9

Summary of changes incl:

Reorderd fields and public get methods in logical order
Extended info now splits client IP address into separate fields IP and Port
Extended info now populates all fields correctly from array returned from SourceServer->splitPlayerStatus()
Added missing private fields and public get methods missing fields.
Added more data to 'extended' toString

I hope these changes are all correct and you can use them in the next release. If you could let me know if ive stuffed anything up (just briefly) that would be good so i know what ive done wrong.

**Comment by koraktor** [comment]
Looks great, thanks.

But I don't know if _"Reorderd fields and public get methods in logical order"_ really is that logical. As far as I can see you reordered the field and methods like they appear in the `status` command. This maybe logical for a server admin, but not for a programmer looking at the code.
Additionally I'm pretty sure that not all servers include IP and port of the client in their `status` output.

Nevertheless, thank you very much!

**Comment by ArgHereBeDragons** [comment]
Fair enough. Shame i cant seem to find a detailed spec on the status command.

**Comment by koraktor** [comment]
Most of this has been done. So I think this can be safely close for now.
