### ISSUE TITLE
String could not be parsed as XML when parsing SteamID

### ISSUE THREAD

**Issue by chyyran** [koraktor/steam-condenser#211]
I'm getting `Exception: String could not be parsed as XML in C:\wamp\www\steam\lib\steamcondenser\steam\community\XMLData.php on line 32`

```
<?php
include 'lib/steamcondenser/steam-condenser.php';
$id = SteamId::create('ron975');
$isOnline = $id->isOnline();
$isInGame = $id->isInGame();
?>
```

[Here is a full image of the exception](http://images.punyman.com/uploads/cd73e193dc41e3eea399.png)

**Comment by koraktor** [comment]
Works for me. 

What version of PHP and Steam Condenser are you using?

**Comment by chyyran** [comment]
It started working again after I reinstalled WAMPServer for some odd reason.. hm.

For the record, I'm using PHP 5.4 and [this build](https://github.com/koraktor/steam-condenser-php/commit/3073358d8bb75bd519d9a7541a592d27d871835f) off GitHub
