### ISSUE TITLE
Exception while parsing "memberSince" tag in user profile

### ISSUE THREAD

**Issue by gcoelho** [koraktor/steam-condenser#215]
Hi,

I´m getting an exception while retrieving and parsing an user profile (method "SteamId.create(String username)". The exception is

com.github.koraktor.steamcondenser.exceptions.SteamCondenserException: XML data could not be parsed.

Debugging Steam Condenser code i found where the exception is thrown. It occurs while parsing  the "memberSince" tag (com.github.koraktor.steamcondenser.steam.community.SteamId - line:358). I tested it with three different users, including "gutomaia" used in Steam Condenser own testcases.

Using Steam Condenser 1.3.2.

Can you verify this please?

Let me know if you need any additional information.

Tks.

**Comment by koraktor** [comment]
Thanks for the report.

Seems like Valve changed the format of the `memberSince` attribute in the XML data. :weary:

**Comment by koraktor** [comment]
I fixed the problem in the commit above. Please use the current code from branch `1.3-stable` until a new version is released.

**Comment by gcoelho** [comment]
Ok! I just check your patch.

Tks!

**Comment by gcoelho** [comment]
I forgot to ask if you have an idea when you are going to release a new version?

Tks!

**Comment by koraktor** [comment]
I hope I'll find some time in the next few days.
