### ISSUE TITLE
GameInventory

### ISSUE THREAD

**Issue by sushant94** [koraktor/steam-condenser#216]
I am not able to use GameInventory class in ruby. It says Uninitialised constant GameInventory. Am i doing something wrong or is the class broken? Need some help with this.

Thank You.

**Comment by koraktor** [comment]
Be sure to call `require 'steam/community/game_inventory'` (or one of its subclasses, e.g. `require 'steam/community/tf2/tf2_inventory'`).

**Comment by sushant94** [comment]
It worked!
Thanks alot!!

**Comment by NerdDiffer** [comment]
Ahhh, why isn't it `steam-condenser`, like the gem name?!?
