### ISSUE TITLE
Too Many open files, if too many timeout

### ISSUE THREAD

**Issue by octera** [koraktor/steam-condenser#23]
In case on timeOut server, we can have an exception too many open file.
You should change :
        if (selector.select(1000) == 0) {
            throw new TimeoutException();
        }
to 
        if (selector.select(1000) == 0) {
            selector.close();
            throw new TimeoutException();
        }
in SteamSocket.java

**Comment by koraktor** [comment]
Java: Fixed IOException "Too many open files" in SteamSocket

Closed by bf8b17ca7e0bcb6367238ac93dce7e2560ac4ee0
