### ISSUE TITLE
Minor update to documentation for steam_group.rb

### ISSUE THREAD

**Issue by blagow** [koraktor/steam-condenser#234]
Working with steam_group.rb, it was pretty confusing that the docs for SteamGroup#fetch said "Loads the members of this group." In actuality, it loads the members and the group_id64, name, headline, summary, and URL.

Caused me several minutes of head scratching before I dove into the code to see why I was getting an XML error. I'd suggest rewriting the comment/docs to say "Loads group data, including members, name, and summary" or something like that.

Probably applies to other versions of steam-condenser, but I've only used the Ruby implementation.

Thanks!

**Comment by koraktor** [comment]
Thanks for reporting this. It also applies to Java and PHP.
