### ISSUE TITLE
WebApi requests being cached

### ISSUE THREAD

**Issue by bfosberry** [koraktor/steam-condenser#240]
This is a bit of an open ended issue, I have added some custom code to the ruby bindings to track current game location, however this location does not get updated. It behaves VERY similarly to caching, the first time the request is made, valid data is pulled down, however on subsequent requests older data is returned. 

What kind of caching is applied to requests? I tried disabling the cachable macro on steam_id.rb.

Here is the code I'm using: https://github.com/bfosberry/steam-condenser-ruby/compare/koraktor:master...summaries

**Comment by koraktor** [comment]
Requests itself are not cached in code, but may be cached by a proxy or something similar.

The `Cacheable` module in the Ruby code only applies to `.new` calls of the affected classes and can always be overridden by calling `#fetch` on an existing instance or adding `true` as the `bypass_cache` parameter on `.new`.

**Comment by bfosberry** [comment]
Gotcha, I'll try that instead of removing the macro. Is there a way to log requests made to steam and responses?

**Comment by koraktor** [comment]
@bfosberry Sorry for the late reply. The current stable code does (i.e. the gem or `1.3-stable`) will log if `$DEBUG` ist `true`. The code in `master` will log using [`SteamCondenser::Logging`](https://github.com/koraktor/steam-condenser-ruby/blob/master/lib/steam-condenser/logging.rb).

**Comment by bfosberry** [comment]
Oh nice, ty sir!

**Comment by koraktor** [comment]
Closing this as it's not a real problem.
