### ISSUE TITLE
Game Description probleme for TF2

### ISSUE THREAD

**Issue by centaureof40** [koraktor/steam-condenser#241]
Hello,

Description of the type of play TF2 appears in "Team Fortress" instead of "Team Fortress 2", it can be corrected ?

Here's an example :

```
 [gameDir] => tf
 [gameDesc] => Team Fortress
 [appId] => 440
```

API PHP 1.3.7

Thank you

**Comment by koraktor** [comment]
I don't know exactly which functionality you're referring to, but there are no hard-coded game names inside Steam Condenser's code.

So this is most likely not changeable.
