### ISSUE TITLE
No response from masterserver

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#244]
Why can not I get a response from GoldSrc masterservers as:
ds-servers.com:27010
ms.game-monitoring.com:27010
ms.killstat.ru:27010
(http://hlmaster.ru/)
I get "java.util.concurrent.TimeoutException" in Java.

**Comment by koraktor** [comment]
These don't seem like official master servers from Valve. So I have no idea if there's a difference in the protocol.

Additionally, are you sure the ports are the correct ones?

**Comment by ghost** [comment]
I m using list of masterservers by http://hlmaster.ru/ for testing.
Status masterserver: On
If click on column "Серверов" (Servers) you may download list of servers from the masterserver.
All this indicates that the master server is running, but through the library "steam-condenser" mastersrver not responding.

**Comment by koraktor** [comment]
Ah I think I understand now. Does one of the other servers from that list work like expected?

**Comment by ghost** [comment]
Not all of the masterserver from the site http://hlmaster.ru/ returns a response using steam-condenser library))
But they are 100% working and excellent work in the embedded serverbrowser in game (CS 1.6).

**Comment by ghost** [comment]
What to do with such servers?

**Comment by koraktor** [comment]
You might try to sniff the packets using Wireshark or similar. There might be slight differences in the implementation of those master servers so the protocol doesn't work like expected.

If that's the case you might get in contact with the operators of those servers. I won't put any effort into Steam Condenser to support non official servers if they don't correctly implement the master server protocol.

**Comment by koraktor** [comment]
Closing this. Feel free to reopen, if those servers implement the master server protocol.
