### ISSUE TITLE
Trying to connect to a source server, immediatly crashes. (Java)

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#248]
I made android app which just connects to my SourceServer. After connect it just crashes.
Does steam condenser support android or i did something wrong? The command is from Usage at koraktor.de.

**Comment by koraktor** [comment]
What error do you get? Steam Condenser will throw an exception on errors, so you'll have to make sure to catch these in your application code anyway.

**Comment by ghost** [comment]
Ehhh, deleted the whole thing, but it said that something with the Activity, like newInstance and something like that... I am really sorry that i delted it, but still this is a issue right?

**Comment by koraktor** [comment]
That’s not really helpful here. Activities are purely Android-related, but there might be other problems involved here.

Feel free to reopen this issue if you can reproduce your problem.
