### ISSUE TITLE
rconAuthenticated never set to true

### ISSUE THREAD

**Issue by tomas-dainovec** [koraktor/steam-condenser#250]
I found this issue when I called `GoldSrcServer.updatePlayers()` (I fount it in Java version) because `rconAuthenticated` is never set to true you have to pass rcon password to the method to get extended player information even if you have set rcon password and can call `rconExec`.

You can see the issue here:
https://github.com/koraktor/steam-condenser-java/blob/master/src/main/java/com/github/koraktor/steamcondenser/servers/GameServer.java#L529

**Comment by koraktor** [comment]
Although `GoldSrcServer` stores the password when using `rconAuth()` (and nothing else), the instance cannot know if the RCON connection is successfully authenticated. GoldSrc's RCON protocol is based on UDP and stateless, so there's no way to tell for neither the client nor the server if the connection was already authenticated.

To effectively implement the state of `rconAuthenticated` for GoldSrc, we'd need to introduce some sort of "check" that will verify the password passed to `rconAuth()`.

I think this might be possible with a reasonable amount of overhead.

**Comment by tomas-dainovec** [comment]
Thanks for your reply. For me more important is to call `updatePlayers` with rcon without passing it as parameter so maybe instead of checking if `rconAuthenticated` it could check if there is rcon password set and if it is, use that?

**Comment by koraktor** [comment]
That would work, but I'd like to share much code as possible for both GoldSrc and Source. Additionally, it result in different behavior when the RCON password is changed server-side.

**Comment by tomas-dainovec** [comment]
I understand your point, however personally I believe it's more important to keep public API consistent. In this case it would work with Source servers as expected but it has different behaviour with GoldSrc servers, actually for GoldSrc server `updatePlayers()` does nothing when called without rcon password. This was confusing...

**Comment by koraktor** [comment]
I did a quick prototype that already looks very promising. Would you mind testing with branch [`issue-250`](https://github.com/koraktor/steam-condenser-java/tree/issue-250)?

**Comment by tomas-dainovec** [comment]
This definetely works for my case, thanks.
