### ISSUE TITLE
socket error in apache log error

### ISSUE THREAD

**Issue by centaureof40** [koraktor/steam-condenser#251]
PHP Warning: socket_read(): unable to read from socket [111]: Connection refused in /var/www/clients/client0/web18/web/test/lib/steam-condenser/lib/Socket.php on line 116

 steam-condenser-php-1.3.8.tar.gz

  SHA1: a532ce66ac7dc8ec654e009b1626e68569306e1e
  MD5:  dd23ef62c6e4baae5ffa2156a5fcb2df

**Comment by koraktor** [comment]
“Connection refused” means that IP address and/or port are wrong and that no server is listening there.
