### ISSUE TITLE
blank page when a player does not have a profile set of steam

### ISSUE THREAD

**Issue by centaureof40** [koraktor/steam-condenser#253]
PHP message: PHP Fatal error:  Uncaught exception 'SteamCondenserException' with message 'This user has not yet set up their Steam Community profile.If you know them encourage him/her to set up their profile and join in on the gaming!' in ...

...steam-condenser/lib/steam/community/SteamId.php(229): SteamId->fetchData()
...test.php(184): SteamId->__construct('765611980764236...')
...index.php(27): include('/var/www/client...')
... #3 {main}
stderr:   thrown in .../steam-condenser/lib/steam/community/SteamId.php on line 250

**Comment by koraktor** [comment]
There's nothing you can do about this problem, but catch this exception and handle it yourself.
