### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by nostacktrace** [koraktor/steam-condenser#256]
Steam-Condenser 1.3.8

java.net.PortUnreachableException not handled in SteamSocket.java:132.
When e.getMessage() in line 133 is null - got NPE.

**Comment by koraktor** [comment]
Sounds valid. I didn't expect there are built-in exceptions that don't have a message.

Reversing the equals statement should fix this. I'll fix this on the `1.3-stable` branch soon.

**Comment by koraktor** [comment]
This is fixed in 34e2df596b0cb6b6b96a2ea5cbefb330cf42e332.
