### ISSUE TITLE
Support Steam ID 3

### ISSUE THREAD

**Issue by nicekiwi** [koraktor/steam-condenser#257]
Need support for calculating or fetching the new Steam ID3: U:1:46674506

**Comment by koraktor** [comment]
It's already supported in `SteamId.convertSteamIdToCommunityId()`.

Any other part where this is needed?

**Comment by nicekiwi** [comment]
Are you sure? It's not the standard steamid or steamid64 or community ID. It's
something new.

On Thursday, 2 October 2014, Sebastian Staudt notifications@github.com
wrote:

> It's already supported in SteamId.convertSteamIdToCommunityId().
> 
> Any other part where this is needed?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/koraktor/steam-condenser/issues/257#issuecomment-57542304
> .

## 

Ezra Sharp
Creative Engineer

KiwiDev

Mobile: (022) 025-9918
Web: www.kiwidev.co.nz

**Comment by koraktor** [comment]
Have a look at the code. It's implemented. Just try it.
