### ISSUE TITLE
Strange issue with rcon?

### ISSUE THREAD

**Issue by zack6849** [koraktor/steam-condenser#258]
Hello, i'm using SteamCondernser's java version in a JSP web application, and im just now running into some VERY strange things, it would seem for some reason creating a `SourceServer` instance, inisializing it, and then calling getPlayers() with the rcon_password in quick succession results in my IP being banned from rcon for "hacking"

Relevant Code:
[`ContextListener.java`](https://gist.github.com/zack6849/c4b80e609019e46815f3)  (Essentially code tht's run when the webapp is deployed)
[`SourceRcon.java`](https://gist.github.com/zack6849/5838b1baa51272c3ff11) (Just an abstraction away from pure steamcondenser with caching and stuff.)
Relevant Output:
[Servlet Output](https://gist.github.com/zack6849/c69a52526d47188c584d)
[Garry's mod console output](https://gist.github.com/zack6849/6e1728ceff8f81329583)  Note: that's literally the only useful information, nothing is shown relevant to rcon before this.

Just before this, i was getting a `RCONNoAuthException: Not authenticated yet.`, I'm not sure how that happened, or how i fixed it, but this is the error that replaced it.

**Comment by zack6849** [comment]
Just Confirmed it was indeed also because i'm trying to get online players immediatley after, commenting out getOnlinePlayerIDs() in my init method removed the error.

Edit: I seem to have narrowed down the error to the `server.initialize()` call, [this is the stactrace](https://gist.github.com/zack6849/cf3a58a71e9150ce20be)

**Comment by zack6849** [comment]
It would appear that restarting my gmod server fixed this, must've been some sort of strange error gmod side, closing this.

**Comment by koraktor** [comment]
Ok, thanks for the report though.
