### ISSUE TITLE
Why always throwing error when using WebApi

### ISSUE THREAD

**Issue by ronjunevaldoz** [koraktor/steam-condenser#259]
Querying Steam Web API: https://api.steampowered.com/IEconItems_570/GetPlayerItems/v0001/?SteamID=76561198073909133&format=json&key=SECRET

**Comment by koraktor** [comment]
What error do you get?

**Comment by ronjunevaldoz** [comment]
the above message was the error message. i believe that the error was thrown because of 30 secs maximum execution? or in the WebAPI class . in the part which "trigger_error was written"

**Comment by koraktor** [comment]
The "message above" is a URL. Just clicking the URL will fail because of the dummy API key. Using my own API key will give the correct result.

Please include the full error message.

**Comment by ronjunevaldoz** [comment]
Im using my own API Key. I have tested it using browser by manually browsing it.

**Comment by koraktor** [comment]
Yes, that's what I assumed. But I can't see the error you get.
Please include it in your report or I have to close this issue.

**Comment by ronjunevaldoz** [comment]
Ok wait. Since i havent used this code for a while . i will try to rerun it again.

**Comment by koraktor** [comment]
Is this still an issue?

**Comment by koraktor** [comment]
Closing this due to missing feedback.
