### ISSUE TITLE
Total Hours Played

### ISSUE THREAD

**Issue by GoblinSystem** [koraktor/steam-condenser#264]
Regarding GameStats of L4D2: getHoursPlayed() give you the number of hours the user played this game during the last 2 weeks. Im interested in getting the _total_ amount of hours a user has spent playing this game.

**Comment by GoblinSystem** [comment]
Sorry bout that, found the desired functionality now (SteamId.getTotalPlayTime("gameid")).

**Comment by koraktor** [comment]
Ok, for L4D(2) there's also `stats.getLifetimeStats()` which includes the total playtime.
