### ISSUE TITLE
SteamId throws exception for private profiles

### ISSUE THREAD

**Issue by VinceG** [koraktor/steam-condenser#265]
Why is throwing an exception for private profiles? this prevents from having at least the basic information like name, 64bit id, avatar, vac banned or not etc. private profiles should not throw an exception IMHO.

Thoughts?

**Comment by koraktor** [comment]
Seems like this is a regression to issue #44 which was fixed a long time ago.

**Comment by koraktor** [comment]
Sorry for the long delay. Is this still an issue? I can’t find a profile where the `privacyMessage` attribute is set that would cause the exception to be raised.
