### ISSUE TITLE
Error 503 Service Unavailable for XML profile API

### ISSUE THREAD

**Issue by CrimsonTautology** [koraktor/steam-condenser#268]
It seems Valve has finally pulled the plug on the deprecated XML API used by this plugin to gather information about a given Steam profile.  We will probably have to switch to the ISteamUser/GetPlayerSummaries interface from the Web Api instead. 

I only use the Ruby version but I assume this affects the Java and PHP libraries as well.

**Comment by koraktor** [comment]
This wouldn’t be the first time that the XML API is unavailable. I guess it might recover within a few minutes or hours. For how long did you experience those errors?

**Comment by CrimsonTautology** [comment]
I noticed it several times last evening in my error logs and went to check again this morning and it was still down.  Just seemed like a long period of time for it to be down.

**Comment by koraktor** [comment]
Ok, maybe Valve is serious now.

Anyway, please leave future comments in issue #195 as this is the main issue for the (pretty stagnant) Web API migration.
