### ISSUE TITLE
PHP - SteamID to Community ID 

### ISSUE THREAD

**Issue by Kilandor** [koraktor/steam-condenser#27]
Due to PHP_INT_MAX which is platform-dependent on a 32 bit version of PHP this limits Integers. This causes the conversion to return incorrect values.

$steamId = explode(':', substr($steamId, 6));
$steamId = $steamId[1] + $steamId[2] \* 2 + 1197960265728;

return "7656".$steamId;

This will allow proper conversion on 32bit systems, or you can explore alternative measures. There are some extensions you can use but I would recommend avoiding this.

I didn't come up with the work around only adapted it.
http://forums.alliedmods.net/showthread.php?t=60899&page=24

Thanks

**Comment by koraktor** [comment]
PHP: Fixed conversion of Steam IDs from STEAM_ID format into 64bit integers on 32bit systems

Closed by 660210fca13b78b640a772f6c4b69e989d6b583d
