### ISSUE TITLE
Encoding in Java

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#272]
NetBeans IDE 8.0.2, Maven, Steam Condenser Java 1.3.9.
I have encoding problems if server have in name Cyrillic character (Windows-1251).
http://s020.radikal.ru/i720/1505/19/9134cd6acf38.png

Maybe somebody look my source code, because I still have problems multithreading (very long response from the game server) unlike the native serverbrowser from Steam.
Please help me, I'm confused, and I can not find a solution.

Source code: http://rghost.ru/7XhHvY7qq

**Comment by koraktor** [comment]
Looks good when built and run on OS X:
![serverbrowser](https://cloud.githubusercontent.com/assets/66112/7783380/28a6b82c-0141-11e5-8aa4-5f184a03699f.png)
