### ISSUE TITLE
Install Steam Condenser and pull request from Server via php

### ISSUE THREAD

**Issue by muuvmuuv** [koraktor/steam-condenser#277]
Hey all,
how can i do this, im really new to dev with JSON etc. I just want to get some Server infos from a CS:GO-Server and want to output all in a var or table to style it later.

Thanks muuvmuuv

**Comment by koraktor** [comment]
Sorry, this is not a bug report. Please ask questions like that on the [mailing list](https://groups.google.com/group/steam-condenser) or e.g. on [stackoverflow](https://stackoverflow.com).
