### ISSUE TITLE
Install Steam-Condenser right

### ISSUE THREAD

**Issue by muuvmuuv** [koraktor/steam-condenser#278]
Hey all,

I think i asked the wrong. I just mean how I can install it with php right, so i can view infos from a CS:GO Server. Dont know how to use this right so please help me out or navigate me to a introduction to isntall sc on my localhost.

Thanks and kind regards 
muuvmuuv

**Comment by koraktor** [comment]
Take the source code from the [releases page](https://github.com/koraktor/steam-condenser-php/releases) for the start.

Please ask questions like that on the mailing list or e.g. on stackoverflow.
