### ISSUE TITLE
Steam Community Avatars

### ISSUE THREAD

**Issue by Kilandor** [koraktor/steam-condenser#28]
The URL returned in the XML as .jpg on it causing the various funcions for returning the url to work incorrectly.

Atleast for the PHP code This will solve it.
$this->imageUrl = (string) substr($profile->avatarIcon, 0, -4);

Also The "Icon" avatar is adding _ which is incorrect and should just be the following
return $this->imageUrl . ".jpg";

----- Edit
Upon further investigation this is needless. At least now anyways they provide the URLs for <avatarIcon>, <avatarMedium>, <avatarFull> It would make more sense to just store these anyways.

**Comment by koraktor** [comment]
PHP: Fixed image URLs in SteamId

Closed by b2782d0608af1826ce2bb4624c5f98d64275ea1a
