### ISSUE TITLE
Ruby - NameError: uninitialized constant SteamCondenser::Community::WebApi

### ISSUE THREAD

**Issue by bfosberry** [koraktor/steam-condenser#282]
2.2.3 :014 > SteamCondenser::Community::WebApi
NameError: uninitialized constant SteamCondenser::Community::WebApi

I think its an import visibility issue, I need to set my steam api key

**Comment by bfosberry** [comment]
basing from git repo works, can you update the gem pls?

**Comment by koraktor** [comment]
The namespaced code hasn't released as a gem, yet. Maybe you build and installed his yourself?

**Comment by bfosberry** [comment]
Unsure what you mean. Let me simplify this down to my problem

Using the gem how do I set the api_key?

**Comment by koraktor** [comment]
Ah that's the problem. Just use `WebApi` without the namespaces.
