### ISSUE TITLE
[java] getPlayers always returns only Max Players

### ISSUE THREAD

**Issue by d35h** [koraktor/steam-condenser#284]
Hey,

I need some help.

When I am trying to fetch all the players from the server, the result is always only one player 'Max Players'.

Code:
 SourceServer server = new SourceServer("144.76.18.36", 20000);

 System.out.println(server.getPlayers("myRconPassword"));

 server.rconAuth("myRconPassword");
 System.out.println(server.rconExec("status"));

Output:
{Max Players=#0 "Max Players", Score: 12, Time: 39603.297}

hostname: *****
version : 1.35.1.1/13511 6211 secure  
udp/ip  : 144.76.18.36:20000  (public ip: 144.76.18.36)
os      :  Linux
type    :  community dedicated
map     : de_cache
gotv[0]:  port 20001, delay 105.0s, rate 32.0
players : 1 humans, 1 bots (12/0 max) (not hibernating)

# userid name uniqueid connected ping loss state rate adr
#45 "SourceTV - www.hiperz.com" BOT active 32
#46 2 "testing acc" STEAM_1:1:15805829 39:44 40 0 active 80000 194.228.13.251:17832
#end

So, it can be seen from the output, that rcon password is correct and the status command works.

Any help appreciated.

D.

**Comment by koraktor** [comment]
See #275. This is a feature of CS:GO.
