### ISSUE TITLE
[Ruby] Rcon authenticate error

### ISSUE THREAD

**Issue by jpalumickas** [koraktor/steam-condenser#286]
Hey,

I'm getting this error when trying to authenticate with Rcon: 

```
TypeError: #<SteamCondenser::Servers::Packets::RCON::RCONGoldSrcRequest:0x007f809b899360 @content_data=#<StringIO:0x007f809b899338>, @header_data=0> is not a symbol nor a string
from /lib/steam-condenser/servers/sockets/goldsrc_socket.rb:146:in `rcon_send'
```

This error I'm getting in `master` branch, but I found that in [6b39915](https://github.com/koraktor/steam-condenser-ruby/commit/6b3991522612728b404cc3e59ce4ef7a571238ac) is working fine. So after this [b8465c2](https://github.com/koraktor/steam-condenser-ruby/commit/b8465c249f1cfe270440fd0c6d7d9d781e725133) something is wrong.

**Comment by koraktor** [comment]
Thanks for reporting.

**Comment by jpalumickas** [comment]
Thanks for fast response :+1:
