### ISSUE TITLE
License Usage query

### ISSUE THREAD

**Issue by pkminer30** [koraktor/steam-condenser#289]
I am looking at using steam condenser as apart of a new project for the "rcon" query framework. I will be charging for the site on completion would this be in violation of your license?

Currently using GameQ on an LGPL license which allows for it to be used aslong as not directly making profit from the developers code. Would i be allowed to use your API as apart of the website to get information like server stats and execute rcon commands on the servers without invalidating your license?

**Comment by koraktor** [comment]
Steam Condenser is licensed under the revised [BSD license](http://choosealicense.com/licenses/bsd-3-clause/), so commercial use is allowed.

**Comment by pkminer30** [comment]
Thank you :D
