### ISSUE TITLE
SRCDS [CS:GO] (php) - Get client ID

### ISSUE THREAD

**Issue by iNilo** [koraktor/steam-condenser#290]
In CSGO (and other source games), status reports the client userid and the client id.

`# 3944 2 "Clayton *FI the Grey" STEAM_1:1:13967715 12:23 78 0 active 128000 0.0.0.0:27005
`

Userid = 3944.
Client id = 2.

When debugging the GameServer.php its not included into the array.

[Dump of $playerData on this line](https://github.com/koraktor/steam-condenser-php/blob/92dde9e3b462e93cc498fe795a712c61eec7051e/lib/SteamCondenser/Servers/GameServer.php#L423)

`Array
(
    [userid] => 3944
    [name] => Clayton *FI the Grey
    [uniqueid] => STEAM_1:1:13967715
    [time] => 08:05
    [ping] => 76
    [loss] => 0
    [state] => active
    [rate] => 128000
    [adr] => 0.0.0.0:27005
)
`

would it be possible to include the clientid ?

Thanks

**Comment by koraktor** [comment]
Shouldn’t that match the index of the player in the array?

``` php
$players = $server->getPlayers();
$player = $players[1]; // "Client ID" - 1
```

I know this second part of the user ID is actively stripped out (IIRC [here](https://github.com/koraktor/steam-condenser-php/blob/92dde9e3b462e93cc498fe795a712c61eec7051e/lib/SteamCondenser/Servers/GameServer.php#L131)).
