### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by JaguXam** [koraktor/steam-condenser#291]
Hello, please help me. I noob in php.
I downloaded php lib and try connect to server.

```
    require $_SERVER['DOCUMENT_ROOT']."/sq/lib/steam-condenser.php";

    $server = new SourceServer('89.179.243.71', 27018);
    $server->initialize();
    print_r($server->getPlayers());

```

not work.

Where i can read manual step - by step on php ?

**Comment by koraktor** [comment]
Please post your code and the full error you get to the [mailing list](http://groups.google.com/group/steam-condenser).

Please do not use the issue tracker for general usage problems.
