### ISSUE TITLE
Java: GoldSrcServer.getPlayers() returns map with SteamPlayers having null SteamID

### ISSUE THREAD

**Issue by realbucksavage** [koraktor/steam-condenser#296]
I am trying to get the SteamID of players on a counter-strike server.
I am using the following code:-

```
List<Server> activeServers = serverDao.getActiveServers();

GameServer gameServerObject = null;

for (Server server : activeServers) {

    gameServerObject = gameServerBA.getGameServerObject(server);

    try {

        Map<String, SteamPlayer> players = gameServerObject.getPlayers();

    } catch (SteamCondenserException e) {

        e.printStackTrace();

    } catch (TimeoutException e) {

        e.printStackTrace();

    }

}
```

Everything is fine, but the `SteamPlayers` in the Map have `null` SteamID.

P.S.:- `gameServerBA.getGameServerObject()` returns an instance of `GoldSrcServer`.

**Comment by koraktor** [comment]
The SteamID can only be obtained using the enhanced `getPlayers()` that uses RCON.

To use it, you will have to know the RCON password of the server and pass it to `getPlayers()`:

``` java
server.getPlayers(rconPassword);
```
