### ISSUE TITLE
GameStats#hours_played returns last 2 weeks, not total play time

### ISSUE THREAD

**Issue by rafaelgonzalez** [koraktor/steam-condenser#297]
Hello,

I am trying to get the hours played for all my games. But the [ruby gem](https://github.com/koraktor/steam-condenser-ruby) seems to return hours for the past two weeks only, not total play time.

Example:

I have played XCOM: Enemy Unknown for 118 hours.

You can see it if you look at it through steam api here: http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=xxx&steamid=76561198002902769&format=json (replace `xxx` with your key)

The one with app_id `200510` has 7082 minutes which is equivalent to 118 hours.

Yet I get this when using the gem:

``` ruby
# Fetching the stats
stats = GameStats.new(76561198002902769, 'xcomenemyunknown')

# Verifying all is accurate
stats.game.name
# => "XCOM: Enemy Unknown" 
stats.game.id
# => "xcomenemyunknown" 
stats.game.app_id
# => 200510 

# Getting play time
stats.hours_played
# => "0" 
```

Not sure if this is a bug, or if I am doing something wrong?

Cheers.

**Comment by rafaelgonzalez** [comment]
Apologies, I have just found [SteamId#total_playtime](http://www.rubydoc.info/gems/steam-condenser/SteamId%3Atotal_playtime) is what I want.

However, I think the documentation of [GameStats#hours_played](http://www.rubydoc.info/gems/steam-condenser/GameStats%3Ahours_played) could be more explicit about returning the last 2 weeks play time.

Also, is there no way to have `#total_play_time` on `GameStats` as well?

**Comment by koraktor** [comment]
No problem.
