### ISSUE TITLE
The specified profile could not be found.

### ISSUE THREAD

**Issue by joelamos** [koraktor/steam-condenser#298]
I keep getting the above message, even when providing URLs to public profiles as below.

`profileUrl = "https://steamcommunity.com/id/joelamos/";`
`long steamId64 = SteamId.create(profileUrl, true, false).getSteamId64();`

**Comment by koraktor** [comment]
`SteamId` does not accept the full URLs. You'll have to use the custom URL part (or Steam ID):

``` java
long steamId64 = SteamId.create("joelamos", true, false).getSteamId64();
```
