### ISSUE TITLE
Not working in real time ?

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#299]
http://i.imgur.com/sCsQMSx.png

I'm online from 10-15 minutes, but this shows always offline. Not updating information for me.
Why ?

**Comment by koraktor** [comment]
That’s interesting. Your normal profile page (http://steamcommunity.com/id/dedihost) shows you have been online a few minutes ago, but the XML data (http://steamcommunity.com/id/dedihost?xml=1) shows "Last Online 111 days ago". Looks like a problem in Steam’s data that can’t be fixed on Steam Condenser’s end.
