### ISSUE TITLE
[PHP] Can't get the master list servers into an array

### ISSUE THREAD

**Issue by rodrigopv** [koraktor/steam-condenser#30]
Hi,

i'm trying to fetch the source master list with this simple code but it won't work

<?php
error_reporting(E_ALL & ~E_USER_NOTICE);

require_once "InetAddress.php";
require_once "steam/servers/MasterServer.php";

$masterServer = new MasterServer(MasterServer::SOURCE_MASTER_SERVER);
$serverArray = $masterServer->getServers(MasterServer::REGION_SOUTH_AMERICA, "\type\d\empty\1\full\1\gamedir\cstrike");

print_r($serverArray);

?>

ERROR:
Fatal error: Uncaught exception 'PacketFormatException' with message 'Master query response has wrong packet header.' in /var/www/html/masterlist/lib/steam/sockets/MasterServerSocket.php:37 Stack trace: #0 /var/www/html/masterlist/lib/steam/servers/MasterServer.php(60): MasterServerSocket->getReply() #1 /var/www/html/masterlist/lib/index.php(7): MasterServer->getServers(255, '\type\d\empty\1...') #2 {main} thrown in /var/www/html/masterlist/lib/steam/sockets/MasterServerSocket.php  on line 37

**Comment by koraktor** [comment]
The code you provided works like expected for me. What version of Steam Condenser are you using? Did you try to monitor you network traffic with a tool like Wireshark?

**Comment by rodrigopv** [comment]
I didn't used any network monitor

I tried in two host using linux..
HOST #1(debian, dreamhost.com): Linux gotti 2.6.31.5-modsign-aufs2-grsec-xeon #1 SMP Fri Nov 20 20:08:17 UTC 2009 x86_64 GNU/Linux
PHP 4.4.9 (cli) (built: Sep 17 2008 12:02:18)

Host #2 (debian, mine): Linux korrupzion3 2.6.26.8 #1 SMP PREEMPT Mon Oct 5 03:55:04 CLT 2009 x86_64 x86_64 x86_64 GNU/Linux
PHP 5.2.10 (cli) (built: Nov 13 2009 11:44:05)

They use the same code and have the same error that i posted above
Oh.. wait, I tried in my local xampp server (windows 7 x64, apache, PHP/5.3.0 ) and it worked flawlessly, in what environment have you tested?

**Comment by koraktor** [comment]
I tested this on MacOS X 10.6.2 and PHP 5.2.11.
The OS shouldn't be a problem. My first idea is, that it's a problem with 64bit.
Windows and OS X 10.6 are both 64bit too, but PHP ist most likely 32bit. At least my system has a 32bit PHP and the Windows package you can download is as far as I know 32bit too.
I will try to check this on a real 64bit PHP.

**Comment by koraktor** [comment]
Did you try the most recent code from the repository or just version 0.9.0? I fixed a similar problem in 425ad28236803187fa013c1338e32948f2aea50b, maybe this solves your problem too.
I just updated my PHP to 5.3.1 (64bit) and I can't reproduce the problem with the current code.

**Comment by rodrigopv** [comment]
I just tried 0.9.0 because I were too lazy to install git and find out how to use it D:. So the problem should be fixed, can someone test or give me command that I should use for cloning the repository?

**Comment by koraktor** [comment]
Cloning the repository is pretty easy, hope it helps:

`git clone git://github.com/koraktor/steam-condenser.git`

**Comment by koraktor** [comment]
Closing this, as there's no response from the issue creator.
