### ISSUE TITLE
PSR-0

### ISSUE THREAD

**Issue by Hackmastr** [koraktor/steam-condenser#300]
Is SteamCondenser PSR-0 compliant?

**Comment by koraktor** [comment]
The `master` branch is [PSR-4](http://www.php-fig.org/psr/psr-4/) compliant.

**Comment by Hackmastr** [comment]
If I install this using composer what branch is downloaded?

**Comment by koraktor** [comment]
Use `dev-master` as version and it will install from `master`.

**Comment by Hackmastr** [comment]
Thank You.
