### ISSUE TITLE
Ruby - CS:GO not working except info_hash, timeout

### ISSUE THREAD

**Issue by 2called-chaos** [koraktor/steam-condenser#301]
Rcon in game works but when I try to use the ruby library it doesn't really work. I get some basic information but anything else doesn't work. Also, I'm not sure if this is a bug or intended, when a command fails it will not retry (e.g. players raises on first try, after that it returns an empty hash). The rcon authentication also times out but `@rcon_authenticated` is set to true.

If have absolutely no idea what the problem is. I tried to increase the timeout to 5 seconds but it still times out. The ports are definitely open.

I collected some debug information in this gist: https://gist.github.com/2called-chaos/f96f0e5ef04b3f0796f13444d442e009

I hope someone has an idea because I totally ran out :-)

**Comment by koraktor** [comment]
See #275 and #284. CS:GO is a bit special when it comes to server queries.

**Comment by 2called-chaos** [comment]
@koraktor Thanks for the reply. I found these issues beforehand but it's not only players it's rcon_auth or rcon_exec, basically everything. I've set `host_info_show 2` and `host_players_show 2` as well. I've also tried to launch the server with `-debug -dev` in the hope to get some debug information on the server side but no luck.

The socket just times out even with a timeout of 10 seconds.

**Comment by 2called-chaos** [comment]
Nevermind, I'm an idiot :-) I copied the example which uses GoldSrcServer but of course I have to use SourceServer. It finally got me when I noticed that the socket was UDP since Go uses TCP.

It's all good now :) Thanks anyways!

PS: This [nodejs solution's readme](https://github.com/pushrax/node-rcon#usage) helped me tons to figure it out.

**Comment by koraktor** [comment]
No problem. Thanks for the update.
