### ISSUE TITLE
Source master server down?

### ISSUE THREAD

**Issue by santisteban** [koraktor/steam-condenser#303]
Is the Source master server down?

I haven't been able to fetch servers since yesterday maintenance.

Always get timed out when trying to connect.

**Comment by koraktor** [comment]
Looks like the servers are down. But sadly, there's nothing I can do on Steam Condenser's end. :disappointed:

**Comment by koraktor** [comment]
@santisteban Is this still an issue for you? There’s currently an active thread on the HLDS mailing list that maybe related to this problem.

**Comment by santisteban** [comment]
@koraktor No, it came back up after like 3 days of being down, or at least the Source one did, don't know about the GoldSrc one.

**Comment by koraktor** [comment]
OK, thanks for the update.
