### ISSUE TITLE
key needed in order to query

### ISSUE THREAD

**Issue by BrutalCSkakan** [koraktor/steam-condenser#306]
I'm getting an error when trying to call on create(steamcommunity), the api tells me that I need to provide my key. But how can I do this?

com.github.koraktor.steamcondenser.exceptions.WebApiException: The Web API request has failed due to an HTTP error: Bad Request (status code: 400).

Bad Request
Required parameter 'key' is missing

**Comment by koraktor** [comment]
You will have to set your API key for most of the API methods:

```java
WebApi.setApiKey("XXXXXXXXXXXXXXXXXXXXXXXXXXXX");
```

If you don't have one already you may register at https://steamcommunity.com/dev/apikey.
