### ISSUE TITLE
Request doesn't provide key, instead it provides "SECRET"

### ISSUE THREAD

**Issue by BrutalCSkakan** [koraktor/steam-condenser#307]
Why is the requests not using the correct API key that's provided with WebApi.setKey("mykey");? 

Instead the key get masked and does the query to https://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?vanityurl=http://steamcommunity.com/id/Swingish/&format=json&**key=SECRET**

Also, accordingly to the docs, the "&format=json" should come after the &key, like this: 
https://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?vanityurl=http://steamcommunity.com/id/Swingish/**&key=SECRET**&format=json

**Comment by koraktor** [comment]
For security reasons, the API key is stripped from the logs.

The order of the HTTP parameters does not matter and is in fact undefined.
