### ISSUE TITLE
Class naming. Why naming 'Server' instead 'Client' ?

### ISSUE THREAD

**Issue by mbto** [koraktor/steam-condenser#308]
Hello. Why you naming all classes with 'Server' instead 'Client'? 
**GameServer, GoldSrcServer, MasterServer, Server, SourceServer...**
In fact, this is misleading the user of your API. In fact, these classes are mini-client to servers.

**Comment by koraktor** [comment]
The question is legitimate, but think about this: The objects are a way to interact with the server itself, get information and send commands.
Calling it `Client` would be even more misleading, IMHO. How would you name them? `SourceClient`? `SourceServerClient`?

**Comment by mbto** [comment]
GameClient, GoldSrcClient, ClientOfMasterServer, Client, SourceClient and package com.github.koraktor.steamcondenser.steam.**clients**
Instances (objects) of your classes perform approximately 5% of the work real client hl.exe, as hlsw.exe etc... They are not "Server".

**Comment by koraktor** [comment]
This might be correct in regard to networking, but the API is on a higher level and the code tries to represent servers. Like said before, the suggested names are misleading themselves.
