### ISSUE TITLE
Private constructor for GameLeaderboard

### ISSUE THREAD

**Issue by Winning117** [koraktor/steam-condenser#309]
Hello I am very new to this API and using APIs in general but I noticed that in GameLeaderboard.java the GameLeaderboard constructor is private. How can you access the leaderboard if it won't let you pass the XMLData to it?

I have tried this to no avail:
`XMLData clucklesXML = new XMLData("http://steamcommunity.com/stats/605250/leaderboards/?xml=1");
		GameLeaderboard cluckles = new GameLeaderboard(clucklesXML);`
It says "The constructor GameLeaderboard(XMLData) is not visible"

**Comment by koraktor** [comment]
You want

`GameLeaderboard.getLeaderboards(String gameName)`

and

`GameLeaderboard.getLeaderboard(String gameName, String name)`

There's a reason the constructor is private.
