### ISSUE TITLE
[php] Allow Setting GameServer.php handleResponseForRequest() repeatOnFailure retries number

### ISSUE THREAD

**Issue by hayden-t** [koraktor/steam-condenser#315]
So you have protected function handleResponseForRequest($requestType, $repeatOnFailure = true) {

which does a repeat once, but quite often i dont get a response with 2 attempts. really this should allow you to set how many times it will retry before giving up.

**Comment by koraktor** [comment]
The reasoning behind the code in place is – and that’s documented for that method – that the server might answer with a challenge reply if e.g. the client asks for the player list and no challenge number was provided.
It’s not intended for error handling of e.g. timeouts or other network issues.

**Comment by hayden-t** [comment]
Ok, i get it, no problem then.
