### ISSUE TITLE
disable logging

### ISSUE THREAD

**Issue by BrutalCSkakan** [koraktor/steam-condenser#316]
Hello! 
Is there a way for me to disable the logging that is going on in the console? It really messes up other debugging logs

**Comment by koraktor** [comment]
What language are you using?

You might want to have a look at issues #186 and (for PHP) #266.

**Comment by BrutalCSkakan** [comment]
Oh yeah I forgot that there's multiple language support. 

This is java, and its these logs that Im talking about

**Comment by BrutalCSkakan** [comment]
![image](https://user-images.githubusercontent.com/8394703/34079810-5aae9a00-e335-11e7-8b23-c7bf663a79b9.png)

**Comment by koraktor** [comment]
The stable Java implementation uses `java.util.logging`. You can reduce the log level, for example:

```java
Logger.getLogger("com.github.koraktor.steamcondenser").setLevel(Level.WARN);
```

**Comment by koraktor** [comment]
@BrutalCSkakan Did the code above help?
