### ISSUE TITLE
How to disable slf4j logger? (Java)

### ISSUE THREAD

**Issue by Antonio112009** [koraktor/steam-condenser#323]
I don't want logger to pop-up all the time on every request I'm sending to server. For me it looks like:

<img width="748" alt="Снимок экрана 2019-04-18 в 1 40 35" src="https://user-images.githubusercontent.com/29264726/56329375-11433680-617b-11e9-8f7f-b4a6615a3fcd.png">

**Comment by gallomimia** [comment]
I don't know what language this is, but this library requires try-catch
logic with error handling

**Comment by koraktor** [comment]
If you want to completely disable slf4j add slf4j-nop as a dependency.

Otherwise configure your slf4j implementation (like log4j) to filter messages from steam-condenser.

**Comment by Antonio112009** [comment]
@koraktor How to do that?

Here's example of my program:
```java
public class Steam_Quary {
    public static void main(String[] args) {
        try {
            ScheduledExecutorService executorService = Executors.newScheduledThreadPool(1);
            executorService.scheduleAtFixedRate(() -> {
                try {
                    InetAddress serverIp = InetAddress.getByName("104.194.8.64");
                    GoldSrcServer server = new GoldSrcServer(serverIp, 27165);
                    server.initialize();
                    System.out.println(server.getServerInfo());
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }, 0, 60, TimeUnit.SECONDS);

        } catch (Exception e){
            e.printStackTrace();
        }
    }
}
```

**Comment by Antonio112009** [comment]
Solved by adding this line 
```java
LogManager.getLogManager().reset();
```

**Comment by koraktor** [comment]
Oh, than you‘re probably using the stable version not the code from `master`.
I didn‘t think about that because you initially asked for slf4j which is only used in `master`.
