### ISSUE TITLE
PHP 8.1 - Socket Extends Error

### ISSUE THREAD

**Issue by pkminer30** [koraktor/steam-condenser#333]
When trying to use this on PHP 8.1 I am getting the following error: 

Fatal error: Class UDPSocket cannot extend final class Socket in scripts/query/steamcondenser/UDPSocket.php on line 22

Looks like there is an issue with one of the classes. Are you able to take a look?

**Comment by koraktor** [comment]
PHP 8 introduced its own `Socket` class conflicting with the existing implementation.

I do not have any plans to support newer PHP versions. Pull requests are welcome, though.

**Comment by robfrawley** [comment]
@koraktor Do you know of anyone who has an interest in taking over the maintenance of this project to support modern PHP `8.x` releases? Or if anyone forked this and took over development?

**Comment by koraktor** [comment]
You might have luck looking at https://github.com/koraktor/steam-condenser-php/forks, but it doesn‘t seem like there‘s a current active fork at the moment.
