### ISSUE TITLE
php8.1 problem & solution

### ISSUE THREAD

**Issue by xE-motionx** [koraktor/steam-condenser#334]
Hi!
Php8.1 brings its own socket with it.
So, the socket that is used needs to be renamed to something else. If not, it will throw an error that the final socket cant be extended.
There are 3 changes necessary to be done:
1. Socket.php:
    Change the name of the class from Socket to something else.
    I used SteamCondenserSocket, for example.
    Line 22:
    `"abstract class steamCondenserSocket {"`
2. TCPSocket.php
    The name of the socket to be extended needs to reflect the first change.
    Line 22:
    `class TCPSocket extends steamCondenserSocket {`
3. UDPSocket.php
    The name of the socket to be extended needs to reflect the first change, too.
    Line 22:
    `class UDPSocket extends steamCondenserSocket {`

Sadly, my lack of knowledge of composer etc. make me unable to create a fork or to create a pull. Therefore: please fix. :)

Kind regards!

**Comment by koraktor** [comment]
See #333, sorry.

**Comment by xE-motionx** [comment]
> See #333, sorry.

No Problem. :)
Thank you anyway!
