### ISSUE TITLE
Avatar URLs are different now

### ISSUE THREAD

**Issue by jouva** [koraktor/steam-condenser#34]
XML now has avatarIcon, avatarMedium and avatarFull separate URLs. avatarIcon is also returning a bad URL as is (in PHP atleast).

**Comment by jouva** [comment]
Oops, looks like this was fixed in #28 but it might be better to use the actual XML entries for future compatibility just in-case? Though I'm not sure which would change first: XML or file names.

**Comment by koraktor** [comment]
Steam Community seems to use some hash algorithm (e.g. MD5 or SHA1) over the contents of the avatar image file to retrieve the file name to use. At least that's what I think is the most reasonable usage of such a system. It would allow to use the same files for the same images, thus saving bandwith.

As I don't expect this to change (at least without an overall change of the whole XML format) I close this one as _won't fix_ for now.
