### ISSUE TITLE
missing profile attribute <friendsSince>

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#37]
Hey,

i notice that the xml attribute <friendsSince> seems to be missing in player profiles.

Regards

**Comment by koraktor** [comment]
This seems to be a new field. I'll add a corresponding property.

**Comment by koraktor** [comment]
I'm sorry. For the moment, this won't make it into the code. The new attribute is only available in the SteamID's XML, not in the friends XML (`/friends?xml=1`) So there's no chance to get the dates for all friends of a user.
Until Valve changes the XML in the future, I won't add this.

**Comment by klaussilveira** [comment]
I have contacted Valve about it, maybe someday in the future they can fix this.

**Comment by koraktor** [comment]
I was in contact with John McCaskey a few months ago about that and other API related things. In fact, he hinted at several improvements, but until now not much has changed. But hey, it's Valve time.

**Comment by koraktor** [comment]
There's now a Web API interface to query friends, but it requires an API key. So I guess this isn't a valid alternative right now.

**Comment by koraktor** [comment]
@idev @klaussilveira What do you guys think about the WebAPI way?

Until now I tried to avoid forcing the user to register for an API key, but there are more and more WebAPI methods which require a key. I guess it won't be that useful in the future to avoid such methods. But for this case I think it's kind of a problem to allow users to load SteamIds without a key, but loading the friends would need one.

Any suggestions?

**Comment by klaussilveira** [comment]
You can throw an exception when a key is not provided and mention the methods that need one in the docs.

**Comment by koraktor** [comment]
An appropriate exception is already thrown by `WebApi`, so I guess this would be fine for most users. But what do you think about the additional hurdle of registering for an API key?

**Comment by koraktor** [comment]
Sorry, I’m going to close this as there’s probably no chance that this might ever be solved on Valve’s end.
