### ISSUE TITLE
PHP - addInformation() offsets are wrong

### ISSUE THREAD

**Issue by jouva** [koraktor/steam-condenser#39]
address, loss, ping and state are off by 1 and need to be increased by 1 each.

**Comment by koraktor** [comment]
Can you please give a live example of this issue? Maybe with a screenshot or similar to prove.

**Comment by koraktor** [comment]
Fixed additional player information via RCON for Source servers

Closed by b4ef6cb9b400e2d7dd3165508ea56888aedaaf9d

**Comment by jouva** [comment]
Why did you delete index 3?

**Comment by koraktor** [comment]
Because the fourth column in Source's `status` output is the time the player is connected. But this value is already known, because the standard `S2A_PLAYER` response includes this value.

To be honest, I don't know why I didn't realize this in the first place.

**Comment by jouva** [comment]
Oh this is true.
