### ISSUE TITLE
PHP - fetchMembers() code invalid

### ISSUE THREAD

**Issue by jouva** [koraktor/steam-condenser#40]
the foreach() goes against each "members" element in the xml, but there's only 1 per page. It's supposed to be going against the steamID64 elements. So it should be:

```
        foreach($memberData->members->steamID64 as $member) {
            array_push($this->members, SteamId::create($member, false));
        }
```

**Comment by koraktor** [comment]
PHP: Fixed fetching of SteamGroup members

Closed by 98713f4decf19a92c9c22c13f9cb139617d35b8b
