### ISSUE TITLE
fetch_friends sometimes return empty list?

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#41]
Hey,

sometimes fetch_friends returns:
["\n\t\t\t","\n\t\t\t"].

But if i open the URL
http://steamcommunity.com/profiles/76561197969493790/friends?xml=1 i get the full list.

I will post more Informations after some research :)

**Comment by koraktor** [comment]
Just tried to reproduce this in a loop - no success. Altough the order of friends changed sometimes, I didn't get any invalid responses.

**Comment by koraktor** [comment]
Closing this, as there doesn't seem to be a problem.
