### ISSUE TITLE
Ruby - Some Profiles are currently not setup

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#42]
Hey,

for example:
https://steamcommunity.com/profiles/76561197984844491?xml=1

fetch fails here because of missing attributes.

Perhaps its possible to check if attribute "privacymessage" is available.

Thanks!

**Comment by koraktor** [comment]
This is already checked: http://github.com/koraktor/steam-condenser/blob/master/ruby/lib/steam/community/steam_id.rb#L97

Do you have 0.10.0 installed?

**Comment by idev** [comment]
Oh, sorry!

I currently working with 0.9.0! 

Can be closed :)
