### ISSUE TITLE
Private Profiles, why not set the available informations?

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#44]
Hey,

just a question, is it possible to set the available infos for private profiles?
(e.g. http://steamcommunity.com/profiles/76561197986835557?xml=1)

Infos like nick, steamid ... are not set though they were available. 
Perhaps the exception raise should happen later in code?

Greetings

**Comment by koraktor** [comment]
Good point... should be fixed.

**Comment by koraktor** [comment]
Fetch available information from profiles not being set up

Closed by 5b6e43391f669799d40c0fb63c8f9cd35ff754f2
