### ISSUE TITLE
ConditionZero Server malformed UTF8

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#45]
Hey,

for 85.131.163.169:27015 i get "illegal/malformed utf-8" on to_json.
it seems to me that tv_name M?@P is the point of fail.

Can you check this?
Thanks for your help!

**Comment by koraktor** [comment]
I checked this against other CZ servers and it seems like the protocol is different than described [here](http://developer.valvesoftware.com/wiki/Server_queries#Source_servers_2). Although those servers send S2A_INFO2 replies (the new format also used by Source, header `0x49`), the format isn't the documented one. The part after the so called EDF seems to be different.

This needs some research. Thanks for pointing this out.

**Comment by koraktor** [comment]
This seems to affect all servers using the new S2A_INFO2 replies, i.e. newer GoldSrc and all Source servers. Seems like the format has changed without notice.

**Comment by koraktor** [comment]
Added parsing of server SteamIDs from S2A_INFO2 replies

Closed by 245e798143ea1dc4194973ff8b23cccbfdb71b92
