### ISSUE TITLE
Using curl as an alternative over file_get_contents

### ISSUE THREAD

**Issue by ghost** [koraktor/steam-condenser#47]
My host has allow_url_fopen flag disabled and in which no way would they enable it for me for security reasons. Without this flag enabled, the steam group page could not be retrieved by the library, hence an error is raised. Fortunately, my host has curl enabled so I had to modify the code a bit (Specifically the SteamGroup.php) and replaced file_get_contents() with curl instead. 

Perhaps it would be better if this was a part of the core implementation instead? So I don't have to keep on changing the code every update. Making file_get_contents a secondary alternative to curl (if curl is not installed on the server).

```
private function getFileContents($url) {
    // make sure curl is installed
    if (function_exists ( 'curl_init' )) {
        // initialize a new curl resource
        $ch = curl_init ();

        // set the url to fetch
        curl_setopt ( $ch, CURLOPT_URL, $url);

        // don't give me the headers just the content
        curl_setopt ( $ch, CURLOPT_HEADER, 0 );

        // return the value instead of printing the response to browser
        curl_setopt ( $ch, CURLOPT_RETURNTRANSFER, 1 );

        // use a user agent to mimic a browser
        curl_setopt ( $ch, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.7.5) Gecko/20041107 Firefox/1.0' );

        $content = curl_exec ( $ch );

        // remember to always close the session and free all resources
        curl_close ( $ch );

        return $content;
    } else {
        // curl library is not installed so we better use something else
         return file_get_contents ($url);
    }
}
```

**Comment by koraktor** [comment]
Seem's like a valuable suggestion. I'll have a look on how to integrate this.
If you like to implement this yourself consider forking my repository and mind some things:
- The fastest way should be the default, I'm not into using cURL with PHP, so maybe cURL is the way to go.
- The decision should be only made once, for all classes using HTTP transport (i.e. community classes).
- There should be a configuration flag or something like that to enable the user to override this. As Steam Condenser currently doesn't need any configuration this might a non-trivial step, but a global constant seems fine for the beginning.

**Comment by koraktor** [comment]
I decided to not implement this. At least there won't be any standard implementation using cURL.
If you you want to, feel free to contribute an optional implementation using cURL as suggested in my last comment.
