### ISSUE TITLE
(Java) Doesn't recognize TF2 bots spawned with tf_bot_add

### ISSUE THREAD

**Issue by wakachamo** [koraktor/steam-condenser#48]
When a bot is added on a Team Fortress 2 server using the command tf_bot_add, said bot does not show up in the "numberOfPlayers" or "numberOfBots" keys of SourceServer's getServerInfo();

If there's anything else needed, please do tell. Thanks in advance. :D

**Comment by koraktor** [comment]
Did you call the server's updateServerInfo() method after adding the bot(s)?

**Comment by wakachamo** [comment]
...it's official. I'm stupid.

For some reason Netbeans wasn't showing updateServerInfo() as an autocomplete option, hence I thought that apparently it wasn't necessary. :P

A million apologies for the waste of time and for the hassle. Thanks for the fantastic support, and keep up the great work. :D

**Comment by koraktor** [comment]
No problem. This is more or less a matter of lacking documentation.
