### ISSUE TITLE
getPlayers should return no nil object

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#5]
On Ruby the getPlayers Method returns also nil Objects, so i have to check nil? before doing something with steamplayer.

greetz

**Comment by koraktor** [comment]
Thanks for your report.
I don't know exactly what's causing this problem right now, but I'll have a look at it.

**Comment by koraktor** [comment]
PHP / Ruby: Minor fixes
- Compact player array in constructor of GameServer
- Ruby: Changed test/query_test.rb back to use MasterServer::SOURCE_MASTER_SERVER constant

Closed by 519ef5b7a914533278cf8b0ae6c54ef064223a25
