### ISSUE TITLE
Search for an user

### ISSUE THREAD

**Issue by Macarse** [koraktor/steam-condenser#52]
Is there any possibility of adding a way to search for an user?

Example:

In my app the user enters "Macar"
and I want to have some sort of auto complete functionality.

**Comment by koraktor** [comment]
Sorry. Right now, there's no good way to do this. The only way would be to parse the HTML of Steam Community's own search. But this is slow, tedious to implement and error-prone.
There's some hope that Steam's new Web API will allow this in the future, but right now, this won't be featured in Steam Condenser.

**Comment by Macarse** [comment]
Ok, thanks for your answer.
All the same, is there a way to check if an users exists instead of doing:

SteamId steamId;
boolean exists = true;
try {
 steamId = SteamId.create("inputByUser");
} catch (SteamCondenserException e) {
 exists = false;
}

**Comment by koraktor** [comment]
No, there's no other way in the moment. Although this might change in the future.
