### ISSUE TITLE
SC [PHP] ERROR 'Unknown packet' on GoldSrcServer: getRules(), rconAuth("rcon1234"), getPlayers("rcon1234"), getReply()

### ISSUE THREAD

**Issue by Odonel** [koraktor/steam-condenser#54]
Hello Koraktor,

ERROR 'Unknown packet with header 0x0 received.' when it used GoldSrcServer functions: getRules(), rconAuth("rcon1234"), getPlayers("rcon1234"), getReply()

<?php
require_once "InetAddress.php";
require_once "steam/servers/GoldSrcServer.php";
$serverIp = new InetAddress("109.68.86.58");
$serverSC = new GoldSrcServer($serverIp, 27016);
$serverSC->initialize();
print_r ($serverSC->getRules());
?>

Apache PHP Log:
[Sat Jul 17 09:34:12 2010] [error] [client X.X.X.X] PHP Fatal error: Uncaught exception 'PacketFormatException' with message 'Unknown packet with header 0x0 received.' in /var/www/httpdocs/include/steam_condenser/steam/packets/SteamPacketFactory.php:90\nStack trace:\n#0 /var/www/httpdocs/include/steam_condenser/steam/packets/SteamPacketFactory.php(121): SteamPacketFactory::getPacketFromData('?sv_rollangle?0...')\n#1 /var/www/httpdocs/include/steam_condenser/steam/sockets/GoldSrcSocket.php(77): SteamPacketFactory::reassemblePacket(Array)\n#2 /var/www/httpdocs/include/steam_condenser/steam/servers/GameServer.php(123): GoldSrcSocket->getReply()\n#3 /var/www/httpdocs/include/steam_condenser/steam/servers/GameServer.php(154): GameServer->getReply()\n#4 /var/www/httpdocs/include/steam_condenser/steam/servers/GameServer.php(177): GameServer->handleResponseForRequest(3, false)\n#5 /var in /var/www/httpdocs/include/steam_condenser/steam/packets/SteamPacketFactory.php on line 90

Thank you very much for the great works you done.

**Comment by koraktor** [comment]
The server you're querying is a Source server, so you should use the `SourceServer` class.

```
<?php
require_once "InetAddress.php";
require_once "steam/servers/SourceServer.php";

$serverIp = new InetAddress("109.68.86.58");
$server = new SourceServer($serverIp, 27016);
$server->initialize();
print_r($server->getRules());
?>
```

That works. ;)
