### ISSUE TITLE
Java implementation should run on Android

### ISSUE THREAD

**Issue by koraktor** [koraktor/steam-condenser#55]
Steam Condenser is currently not compatible with Android's Dalvik VM.

fcerenza and Macarse are currently working on a series of Android patches in [fcerenza/steam-condenser@android](http://github.com/fcerenza/steam-condenser/commits/android).

**Comment by txdv** [comment]
Doesn't seem to me that they are working at all.

**Comment by koraktor** [comment]
Seems so. Maybe I'll contact one of them to get that code back they had in their repository before they deleted it.

**Comment by ynleborg** [comment]
Any info on that code?

**Comment by koraktor** [comment]
Sadly not, it seems they have deleted their changes. I did ask for a copy, but they only have a custom created solution right now.

Any volunteers?

**Comment by txdv** [comment]
Java sucks, all the getters and setters in the code look ulgy.
