### ISSUE TITLE
Add Alien Swarm statistics

### ISSUE THREAD

**Issue by koraktor** [koraktor/steam-condenser#56]
Once Valve has fixed the XML data for Alien Swarm stats (see http://steamcommunity.com/id/koraktor/stats/alienswarm?xml=1 for the currently empty stats data) this should be added.

**Comment by txdv** [comment]
A lot of stuff there :D

**Comment by ynleborg** [comment]
This is proper link to statistics http://steamcommunity.com/id/ynleborg/stats/AlienSwarm/achievements?tab=achievements&xml=all

unfortunately schema is different, new parser is needed.

**Comment by koraktor** [comment]
Looks good, http://steamcommunity.com/id/koraktor/stats/alienswarm?xml=all works too. Now I can start working on it. Thanks.

PS: How did you find out that URL?

**Comment by ynleborg** [comment]
yeah, i don't know why steam api is so messed up :/ I got it from giantbomb or raptr forum. GiantBomb still don't tracking alien swarm achievement, although raptr and dev.zr40.nl do.

**Comment by koraktor** [comment]
This is now done for Ruby.

**Comment by koraktor** [comment]
Java and PHP now also have stats for Alien Swarm.
