### ISSUE TITLE
S2A_INFO2_PACKET.php Line 52, Typo?

### ISSUE THREAD

**Issue by uniflare** [koraktor/steam-condenser#57]
Trying to access property that doesn't exist, Undefined Property getLong.

Should be:
                $this->serverId = $this->contentData->getLong() | ($this->contentData->getLong() << 32);

-cb-

**Comment by koraktor** [comment]
PHP: Fixed typo in S2A_INFO2_Packet

Closed by cf7966fffab2ed7e15bc80dc8416038b707dd0e7

**Comment by koraktor** [comment]
Thanks. This is correct.
