### ISSUE TITLE
[RUBY] StringIO Additions is causing problems

### ISSUE THREAD

**Issue by webdestroya** [koraktor/steam-condenser#59]
Whenever I include the StringIO additions you made, it seems to generate errors when I call anything that uses something from your package.

```
 You have a nil object when you didn't expect it!
 You might have expected an instance of Array .
 The error occurred while evaluating nil.[]
```

This is caused by the def strings method at the bottom of the class. If I remove that method, it appears to work, but I know I am breaking something.

**Comment by webdestroya** [comment]
I am using Rails 3.0. It seemed to work OK when using Rails 2.3.8

**Comment by webdestroya** [comment]
I was able to fix it (it would seem) by renaming `StringIO` to be `SteamStringIO` and have it extend `StringIO`. That seemed to fix the name collisions, while still allowing your app to function.

**Comment by koraktor** [comment]
I just checked Rails 3 and any dependent gems for additions to Ruby's StringIO class, but couldn't find any. I also checked some other common gems for any StringIO extensions. Maybe you use other gems that change the StringIO implementation.

If you want, you may also try renaming the `string` method as it's the only thing I'm changing that may interfere with other gems.

**Comment by webdestroya** [comment]
I know it is caused by the `string` method. If I comment out that method in the file, everything performs just fine. (Except that it then breaks the game server query calls). I was able to fix it by renaming your `StringIO` to be `SteamStringIO` and extend it, but since that change isn't in the gem, it limits the usefulness of my change.

**Comment by koraktor** [comment]
Fixed compatibility issues with StringIO additions

Closed by f9b241ca77373602de479113837eeb40a85cbbc6

**Comment by koraktor** [comment]
I no longer overwrite `StringIO#string`. It's called `StringIO#cstring` now.

**Comment by webdestroya** [comment]
Sweet! Thanks for fixing that. Will this change post to rubygems anytime soon?

**Comment by koraktor** [comment]
Sorry, forgot to upload it. Just pushed the update to RubyGems. Thanks for the reminder.
