### ISSUE TITLE
GoldSrcServer returns only one Player on get_players

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#6]
Hey,

on GoldSrcServer get_players seems to responding only on Player.
The returned Array has the size of the players on the server, but only one player is in there.

Greetings!

**Comment by koraktor** [comment]
Workaround for GoldSrc servers not sending player IDs
- Changed S2A_PLAYER_Packet in PHP and Ruby to manage the player array safely, ignoring player IDs

Closed by 7914a304289911b4538272bf1243fdfebf552264
