### ISSUE TITLE
PHP - Missing Base file include, and define bug

### ISSUE THREAD

**Issue by Kilandor** [koraktor/steam-condenser#60]
lib/steam-condenser.php is not included in any of the "test" files which cause a complete failure.

Also while minor
define(STEAM_CONDENSER_PATH, dirname(__FILE__) . '/');
define(STEAM_CONDENSER_VERSION, '0.11.2');

The defines should be quoted or they throw notice, php corrects the problem and it still works however quoting it will fix the issue outright
define('STEAM_CONDENSER_PATH', dirname(__FILE__) . '/');
define('STEAM_CONDENSER_VERSION', '0.11.2');

**Comment by koraktor** [comment]
This has been fixed in d195ab68635b9d53c9a240330d80d8de646ed079 and 879027d006be91d00425e22f2652fc09494dbb01 respectively.
