### ISSUE TITLE
Ruby 1.9.2: super from singleton method that is defined to multiple classes is not supported

### ISSUE THREAD

**Issue by mollstam** [koraktor/steam-condenser#65]
Instantiating a new SourceServer with Ruby 1.9.2 raises the following issue:
    NotImplementedError (super from singleton method that is defined to multiple classes is not supported; this will be fixed in 1.9.3 or later)

Steps to reproduce:
    SourceServer.new(IPAddr.new("127.0.0.1"));

I'm not sure if there's anything worth doing to steam-condenser, or if the issue is to be resolved in Ruby. Guess I'll have a poke around the code, just wanted to also file a report.

More information about the general issue can be found here: http://gist.github.com/455547

**Comment by koraktor** [comment]
First of all, thanks for your report.
<strike>Strange thing is I'm not using the kind of definition used in the Gist.</strike>
Nevertheless I will have a look into this.

Ok, my (pretty unrubyish) definition of an abstract class causes this issue. I will replace it with a solution in a more Ruby like fashion.
In the meantime feel free to remove the line `include AbstractClass` from any affected classes.

**Comment by mollstam** [comment]
Thanks for the quick the reply. Was just about to write and say that I removed AbstractClass and it all worked out for me (connecting and rcon, all I need).

Cheers, good luck and stay awesome.

**Comment by koraktor** [comment]
Ruby: Removed unrubyish AbstractClass

This also resolves problems with Ruby 1.9.2.

Closed by 52432631123270be49e22d3bba93aa3f0f4cca7c
