### ISSUE TITLE
Java SteamGroup implementation is faulty

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#66]
It doesn't Cache automatically, the getting the memberlist with getMemberCount doesn't work either.

**Comment by koraktor** [comment]
Caching needs some work in both Java and PHP.

`SteamGroup#getMemberCount()` works like expected. It won't get the member list though, like the name says only the member count. This is most useful for huge groups, where getting all members takes a lot of time.

**Comment by txdv** [comment]
I thought it doesn't work correctly but while creating the C# version (I was looking at the Java version) I typed /memberlist and not /memberslist, missed the s, that's why I didn't got the list.

Caching is only used in SteamID and SteamGroup, right?

**Comment by koraktor** [comment]
Yes, at least right now.

**Comment by koraktor** [comment]
Java: Enabled caching in SteamGroup and SteamId

Closed by c2882129649c9cf204ce8f1b92ba9647a11fe348
