### ISSUE TITLE
favwpn renamed to favwpnid

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#67]
In CSSStats.java:

this.lastMatchStats.put("favoriteWeapon", lastMatchStats.getElementsByTagName("favwpn").item(0).getTextContent());

I have personally lookd up the sight, it's called favwpnid now

**Comment by koraktor** [comment]
Ok, this should be fixed then.

**Comment by koraktor** [comment]
Fix for a change in CS:S stats XML data

The favorite weapon of the last game is now an numeric ID. Right now, there
seems no way to tell the weapon name from this ID programatically.

Closed by 7ae52f41e9432f9a44e9f299a1295ac424a35fad
