### ISSUE TITLE
AbstractL4DStats: Wrong item retrieved

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#72]
in the constructor:
  public AbstractL4DStats(Object steamId, String gameName)
      throws SteamCondenserException {
    super(steamId, gameName);
...
this.mostRecentGame.put("timePlayed", mostRecentGameNode.getElementsByTagName("timeplayed").item(0).getTextContent());

The xml item is called time

**Comment by koraktor** [comment]
Just another one, thanks.

**Comment by koraktor** [comment]
Java: Fixed another bunch of problems in L4D related stats

Closed by 8d7f945387f2bedc7f37df89c02d6c9dd97b3fc7
Closed by 8d7f945387f2bedc7f37df89c02d6c9dd97b3fc7
Closed by 8d7f945387f2bedc7f37df89c02d6c9dd97b3fc7
