### ISSUE TITLE
Duplicate of getWeaponStats in AbstractL4DStats and L4DStats

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#73]
These two functions are completely alike, I would suggest to remove the one in the abstract class

**Comment by koraktor** [comment]
Java: Fixed another bunch of problems in L4D related stats

Closed by 8d7f945387f2bedc7f37df89c02d6c9dd97b3fc7
Closed by 8d7f945387f2bedc7f37df89c02d6c9dd97b3fc7
Closed by 8d7f945387f2bedc7f37df89c02d6c9dd97b3fc7
