### ISSUE TITLE
Wrong type in L4D2Stats

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#75]
mapHash.put("name", Integer.parseInt(mapData.getElementsByTagName("fullname").item(0).getTextContent()));

It's not a string.

Please write testcases testing this against me: 
id: toxedvirus
community: 76561197989711328
steamid: "STEAM_0:0:14722800"

**Comment by txdv** [comment]
I mean its a string, not an integer

**Comment by koraktor** [comment]
Java: Fixed another bunch of problems in L4D related stats

Closed by 8d7f945387f2bedc7f37df89c02d6c9dd97b3fc7
Closed by 8d7f945387f2bedc7f37df89c02d6c9dd97b3fc7
Closed by 8d7f945387f2bedc7f37df89c02d6c9dd97b3fc7
