### ISSUE TITLE
Escape XML code

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#78]
view-source:http://steamcommunity.com/id/toxedvirus?xml=1

This is a google-chrome link, soe remove view-source in other browsers..

The thing is that XML escapes stuff like < in XML code, I dunno if Java handles that automatically when retrieving the text version, but in  C# you have to do it yourself.

**Comment by koraktor** [comment]
Good to know, have to check that.

**Comment by txdv** [comment]
Check out the summary field in the link i gave you.

**Comment by psychonic** [comment]
This affects php's SimpleXML as well.

On another note, Steam seems to only be escaping <  >
The following three characters are left intact  "  '  &
