### ISSUE TITLE
get_ping timeout

### ISSUE THREAD

**Issue by idev** [koraktor/steam-condenser#8]
Hey,

if i call get_ping after a server.init i get a timeout.
(Noticed with SourceServer class)

greetings

**Comment by koraktor** [comment]
Can't reproduce this. Are you sure the server is reachable?
Additionally I can't imagine why `#init` could influence `#get_ping` / `#update_ping`.

**Comment by idev** [comment]
Please close the issue, something was wrong with my code ;)
