### ISSUE TITLE
server.server_info is not programmed the ruby way

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#83]
i = server.server_info
 p "#{i["map_name"]} #{i["number_of_players"]}/#{i["max_players"]}"

This makes me really sad as a ruby programmer.
What I would like to see is the capability of i[:map_name], i[:number_of_players] and
i.map_name, i.number_of_players.

And I guess you can find this everywhere where a hash is returned :)

**Comment by koraktor** [comment]
Yep, that's true. Most of the basic parts of Steam Condenser were created when I wasn't really experienced with Ruby. In the beginning Java was the primary implementation. Today it's Ruby, but I never really had time to rework the old unrubyish code, e.g. `AbstractClass`.
