### ISSUE TITLE
server_info should hold the ip address aswell

### ISSUE THREAD

**Issue by txdv** [koraktor/steam-condenser#84]
In ruby the hostname gets resoluted like this: IPSocket.getaddress args
The ip address in the process should be saved in the server_info so there would be no redudancy for the user (he wouldn't have to check it again)

**Comment by xewl** [comment]
I second this opinion.

**Comment by koraktor** [comment]
IP and host name handling respectively should be reworked and unified for all three implementations.

**Comment by koraktor** [comment]
Since commit f1ffe58c787757dc07164aaee32ef73fbce79b3a, all servers are now subclasses of `Server` which provides getters for host names and IP addresses.
