### ISSUE TITLE
Fetching never played CS:S statistics.

### ISSUE THREAD

**Issue by ynleborg** [koraktor/steam-condenser#86]
I've never played game, so this line (and next):

steamcondenser.steam.community.css.CSSStats.<init>(CSSStats.java:100)

gives me

java.lang.ArithmeticException: / by zero

**Comment by koraktor** [comment]
Ruby / Java: Fixed possible division by zero in CSSStats

Closed by 4f98c075c5e0695f694e0d0ddb59ac4e453bdc7b
