### ISSUE TITLE
throwing exceptions on socket timeout

### ISSUE THREAD

**Issue by vaniok** [koraktor/steam-condenser#91]
Hello,

Is it really a good idea to throw exceptions such as `throw new Exception("Could not read from socket.");` ? 'throw' halts script execution, which will result in broken content if steam-condenser is used as an 'include' on a website.
Much more suitable method would be to use error_log() and let web-admins trace errors.

**Comment by koraktor** [comment]
You can always catch the exception and do the handling yourself, so you're free to do whatever you want:

```
 try {
     $server->getInfo();
 } catch(Exception $e) {
     trigger_error($e->getMessage());
 }
```

**Comment by vaniok** [comment]
Damn it, I really have to stop finding the hard-way solutions for simple stuff ... Thank's for the solution.
