### ISSUE TITLE
OB (TF2 !?) Servers will always throw "TimeoutException" when trying to query them

### ISSUE THREAD

**Issue by p1ngb4ck** [koraktor/steam-condenser#96]
Hi ..
when trying to query a TF2-Server, I am always getting TimeoutExceptions. Just using the example code here on github ..
if I query a L4D or L4D2 - server, everything works fine.
This must have changed with one of the last updates, my php-script integrated in my clanpage worked fine before, suddenly it throws exceptions.

**Comment by koraktor** [comment]
There was an update yesterday with the following change:
- Improved engine handling of server queries

Seems like this broke something. I'll investigate.

**Comment by p1ngb4ck** [comment]
Problem occurs with HL2 Servers also, after latest update

**Comment by p1ngb4ck** [comment]
great, quick response, TY =)

**Comment by koraktor** [comment]
From the HLDS mailing list:

> Terrific. It seems that with this update the servers stopped responding to A2A_PING.
> Guess I have to use A2S_INFO now even though I just want to know if the server is alive."

Seems like don't using the servers' `init()`, `getPing()` and `updatePing()` is a workaround.

I'll watch the progress on this issue, maybe Valve will fix this soon.

**Comment by koraktor** [comment]
By the way, this is now fixed in [master](https://github.com/koraktor/steam-condenser) and should be available in a new version soon.
