### ISSUE TITLE
Wrong password detection?

### ISSUE THREAD

**Issue by wakachamo** [koraktor/steam-condenser#97]
From what I can tell (at least in Java), there is no way to detect if a password is wrong when trying to connect to a server. Am I missing something?

**Comment by koraktor** [comment]
`SourceServer#rconAuth()` returns a `boolean`, so you can see if your password was correct. `GoldSrcServer#rconAuth()` does always return `true`, because there's no such connection authentification using GoldSrc's protocol, which is based on UDP.

**Comment by wakachamo** [comment]
Oh right, I see now, haha. Must've missed that. Thanks! :D
