### ISSUE TITLE
Sudden appearance of TimeoutException

### ISSUE THREAD

**Issue by Gobie** [koraktor/steam-condenser#98]
This TimeoutException as response to query CS:S servers started to be thrown on 01/29/2011 consistently. It happened occasionally before, but it was like once a day. Since I didn't change the script, it seems the server side changed. But since I query public servers, where I get no FTP nor RCON priviliges, I can't check, what they changed.
But as I checked the CS:S news, there have been 2 updates 01/25 and 01/27. Is it possible these updates messed that up?

```
exception 'TimeoutException' in /path/lib/steam/sockets/SteamSocket.php:80
Stack trace:
\#0 /path/lib/steam/sockets/SourceSocket.php(28): SteamSocket-&gt;receivePacket(1400)
\#1 /path/lib/steam/servers/GameServer.php(123): SourceSocket-&gt;getReply()
\#2 /path/lib/steam/servers/GameServer.php(212): GameServer-&gt;getReply()
\#3 /path/lib/steam/servers/GameServer.php(114): GameServer-&gt;updatePing()
\#4 /path/test.php(12): GameServer-&gt;initialize()
\#5 {main}
```

Test PHP code:
Changing the timeout doesn't affect it at all.

```
<?php

error_reporting(E_ALL & ~E_USER_NOTICE);

require_once "lib/steam-condenser.php";

try {

  SteamSocket::setTimeout(10000);

  $server = new SourceServer(new InetAddress("87.98.139.119"), 27035);
  $server->initialize();

} catch (Exception $e) {

  echo $e->__toString();

}

?>
```

They are all public Source servers
RedLine
87.98.139.119:27035
87.98.139.119:27035
87.98.185.211:27015
Soylent
78.143.57.114:27015

**Comment by koraktor** [comment]
This is most probably the same error as #96.

Valve changed the handling of queries in a recent update and this broke the ability to ping the servers. The workaround is to not use the `initialize()`, `getPing()` and `updatePing()` methods.

Right now, I don't want to remove/rewrite this feature completely, because I don't know if this behaviour is intended by Valve or a bug. If Valve doesn't fix it in the near future, I will fix it in Steam Condenser.

**Comment by Gobie** [comment]
I'm really amazed by such a quick response.
Thank you for your explanation.

**Comment by koraktor** [comment]
By the way, this is no fixed in [master](https://github.com/koraktor/steam-condenser) and should be available in a new version soon.
